-- Staging schema reconstructed from available local data; not original server source.
BEGIN;
CREATE TABLE IF NOT EXISTS public."ai_feature_costs" ("id" text PRIMARY KEY,"feature_key" text,"feature_label" text,"credit_cost" numeric,"active" boolean,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."avatar_frames" ("id" text PRIMARY KEY,"name" text,"slug" text,"rarity" text,"frame_image_url" text,"is_animated" boolean,"animation_css" text,"price_credits" numeric,"is_active" boolean,"is_limited" boolean,"max_supply" text,"sold_count" numeric,"sort_order" numeric,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."avatar_gallery" ("id" text PRIMARY KEY,"user_id" text,"image_object_key" text,"display_name" text,"created_at" text);
CREATE TABLE IF NOT EXISTS public."avatar_listings" ("id" text PRIMARY KEY,"nft_id" text,"seller_user_id" text,"price_credits" numeric,"min_price_credits" numeric,"status" text,"created_at" text,"sold_at" text);
CREATE TABLE IF NOT EXISTS public."avatar_nfts" ("id" text PRIMARY KEY,"image_object_key" text,"style_key" text,"mint_number" numeric,"display_name" text,"owner_user_id" text,"creator_user_id" text,"total_owners" numeric,"tournament_wins" numeric,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."avatar_style_limits" ("id" text PRIMARY KEY,"style_key" text,"max_supply" numeric,"current_supply" numeric,"created_at" text);
CREATE TABLE IF NOT EXISTS public."avatar_trades" ("id" text PRIMARY KEY,"nft_id" text,"listing_id" text,"seller_user_id" text,"buyer_user_id" text,"price_credits" numeric,"platform_fee" numeric,"seller_received" numeric,"created_at" text);
CREATE TABLE IF NOT EXISTS public."bans" ("id" text PRIMARY KEY,"federation_id" text,"banned_by_user_id" text,"target_type" text,"player_profile_id" text,"team_id" text,"team_scope" text,"reason" text,"regulation_id" text,"is_global" boolean,"starts_at" text,"ends_at" text,"active" boolean,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."bracket_display_config" ("id" text PRIMARY KEY,"card_width" numeric,"connector_gap" numeric,"card_border_radius" numeric,"emblem_size" numeric,"emblem_img_size" numeric,"font_size_name" numeric,"font_size_score" numeric,"font_size_vs" numeric,"font_size_round_header" numeric,"glow_intensity" numeric,"show_schedule" boolean,"show_status_bar" boolean,"show_glow_effects" boolean,"show_game_expand" boolean,"show_md_label" boolean,"standings_font_size" numeric,"standings_emblem_size" numeric,"standings_show_plan_badge" boolean,"standings_show_advance_zone" boolean,"standings_show_points_bar" boolean,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."bracket_rounds" ("id" text PRIMARY KEY,"bracket_id" text,"round_number" numeric,"name" text,"metadata_source" text);
CREATE TABLE IF NOT EXISTS public."brackets" ("stage_id" text,"bracket_type" text,"metadata_source" text,"id" text PRIMARY KEY);
CREATE TABLE IF NOT EXISTS public."champion_roster_snapshots" ("id" text PRIMARY KEY,"tournament_id" text,"entrant_id" text,"player_profile_id" text,"role" text,"handle" text,"created_at" text);
CREATE TABLE IF NOT EXISTS public."combo_effects" ("id" text PRIMARY KEY,"collection_id" text,"required_count" numeric,"combo_tier" text,"effect_type" text,"effect_css" text,"effect_animation_url" text,"badge_label" text,"badge_color" text,"created_at" text);
CREATE TABLE IF NOT EXISTS public."cosmetic_bundle_items" ("id" text PRIMARY KEY,"bundle_id" text,"cosmetic_id" text);
CREATE TABLE IF NOT EXISTS public."cosmetic_bundles" ("id" text PRIMARY KEY,"name" text,"collection_id" text,"bundle_tier" text,"discount_pct" numeric,"price_credits" numeric,"is_active" boolean,"created_at" text);
CREATE TABLE IF NOT EXISTS public."cosmetic_collections" ("id" text PRIMARY KEY,"name" text,"slug" text,"rarity" text,"theme_color" text,"is_limited" boolean,"max_supply" numeric,"sold_count" numeric,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."cosmetics" ("id" text PRIMARY KEY,"name" text,"type" text,"collection_id" text,"rarity" text,"animation_url" text,"preview_url" text,"price_credits" numeric,"is_active" boolean,"sort_order" numeric,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."countries" ("id" text PRIMARY KEY,"iso2" text,"name" text,"created_at" text);
CREATE TABLE IF NOT EXISTS public."credit_packages" ("id" text PRIMARY KEY,"credits" numeric,"price_cents" numeric,"currency" text,"label" text,"popular" boolean,"active" boolean,"stripe_price_id" text,"created_at" text);
CREATE TABLE IF NOT EXISTS public."credit_transactions" ("created_at" text,"user_id" text,"amount" numeric,"balance_after" numeric,"type" text,"description" text,"id" text PRIMARY KEY);
CREATE TABLE IF NOT EXISTS public."draft_plan_limits" ("id" text PRIMARY KEY,"plan_key" text,"max_players_per_draft" numeric,"max_teams_per_draft" numeric,"max_active_drafts" numeric,"can_use_premium_trophy" boolean,"can_create_private" boolean,"can_use_custom_team_names" boolean,"can_view_stats" boolean,"created_at" text,"updated_at" text,"default_entry_cost_credits" numeric,"creator_share_pct" numeric);
CREATE TABLE IF NOT EXISTS public."drafts" ("id" text PRIMARY KEY,"creator_user_id" text,"name" text,"game_id" text,"country_id" text,"federation_id" text,"mode" text,"format" text,"teams_count" numeric,"players_per_team" numeric,"total_slots" numeric,"allow_substitutes" boolean,"subs_per_team" numeric,"entry_cost_credits" numeric,"trophy_id" text,"tournament_id" text,"status" text,"is_private" boolean,"invite_code" text,"cooldown_until" text,"created_at" text,"updated_at" text,"champion_prize_pct" numeric,"real_prize_description" text);
CREATE TABLE IF NOT EXISTS public."eafc_newgen_matches" ("match_id" numeric,"match_type" text,"platform" text,"match_timestamp" numeric,"match_date" text,"home_club_id" numeric,"home_club_name" text,"away_club_id" numeric,"away_club_name" text,"home_goals" numeric,"away_goals" numeric,"home_assists" numeric,"away_assists" numeric,"home_result" text,"away_result" text,"time_ago_number" numeric,"time_ago_unit" text,"raw_json" jsonb,"created_at" text,"home_shots" numeric,"away_shots" numeric,"home_passes_made" numeric,"away_passes_made" numeric,"home_pass_attempts" numeric,"away_pass_attempts" numeric,"home_tackles_made" numeric,"away_tackles_made" numeric,"home_tackle_attempts" numeric,"away_tackle_attempts" numeric,"home_saves" numeric,"away_saves" numeric,"home_rating_sum" numeric,"away_rating_sum" numeric,"id" text PRIMARY KEY);
CREATE TABLE IF NOT EXISTS public."eafc_newgen_player_positions" ("position_id" numeric,"code_ptbr" text,"code_es" text,"code_en" text,"code_pt" text,"code_ita" text,"code_ale" text,"code_fr" text,"codes_ptbr" jsonb,"codes_es" jsonb,"codes_en" jsonb,"codes_pt" jsonb,"codes_ita" jsonb,"codes_ale" jsonb,"codes_fr" jsonb,"label_ptbr" text,"label_es" text,"label_en" text,"label_pt" text,"label_ita" text,"label_ale" text,"label_fr" text,"notes" text,"created_at" text,"id" text PRIMARY KEY);
CREATE TABLE IF NOT EXISTS public."easy_tournament_allowed_games" ("id" text PRIMARY KEY,"game_id" text,"created_at" text);
CREATE TABLE IF NOT EXISTS public."easy_tournament_settings" ("id" text PRIMARY KEY,"min_plan_required" text,"max_active_tournaments_pro" numeric,"max_active_tournaments_ultra" numeric,"max_teams_pro" numeric,"max_teams_ultra" numeric,"allow_custom_teams" boolean,"allow_platform_teams" boolean,"allow_md5" boolean,"allow_groups" boolean,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."ecosystem_game_cards" ("id" text PRIMARY KEY,"image_url" text,"title" text,"subtitle" text,"glow_color" text,"game_ids" jsonb,"sort_order" numeric,"is_active" boolean,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."elo_federation_seasons" ("id" text PRIMARY KEY,"federation_id" text,"season_id" text,"status" text,"previous_federation_season_id" text,"current_config_version_id" text,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."elo_season_teams" ("id" text PRIMARY KEY,"federation_season_id" text,"team_id" text,"season_tier_id" text,"tier_position" numeric,"elo_rating" numeric,"matches_played" numeric,"wins" numeric,"draws" numeric,"losses" numeric,"status" text,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."elo_season_tiers" ("id" text PRIMARY KEY,"federation_season_id" text,"code" text,"name" text,"rank" numeric,"active" boolean,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."elo_tier_version_rules" ("id" text PRIMARY KEY,"config_version_id" text,"season_tier_id" text,"max_teams" numeric,"initial_elo" numeric,"floor_elo" numeric,"promotion_spots" numeric,"relegation_spots" numeric,"created_at" text);
CREATE TABLE IF NOT EXISTS public."entity_slugs" ("slug" text,"entity_type" text,"entity_id" text,"created_at" text,"id" text PRIMARY KEY);
CREATE TABLE IF NOT EXISTS public."entity_visual_overrides" ("id" text PRIMARY KEY,"entity_type" text,"entity_id" text,"config" jsonb,"updated_at" text,"updated_by" text);
CREATE TABLE IF NOT EXISTS public."entrants" ("id" text PRIMARY KEY,"tournament_id" text,"player_profile_id" text,"team_id" text,"seed" numeric,"created_at" text,"easy_custom_team_id" text);
CREATE TABLE IF NOT EXISTS public."fantasy_achievements" ("id" text PRIMARY KEY,"game_id" text,"name" text,"description" text,"icon" text,"rarity" text,"category" text,"coin_bonus" numeric,"xp_bonus" numeric,"unlock_condition" jsonb,"repeatable" boolean,"is_active" boolean,"is_seasonal" boolean,"glow_color" text,"sort_order" numeric,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."fantasy_league_members" ("id" text PRIMARY KEY,"league_id" text,"user_id" text,"total_points" numeric,"round_points" numeric,"rank" text,"joined_at" text,"budget_remaining" numeric);
CREATE TABLE IF NOT EXISTS public."fantasy_lineup_players" ("id" text PRIMARY KEY,"lineup_id" text,"player_profile_id" text,"position_slot" text,"is_captain" boolean,"fantasy_points" numeric,"purchase_value" numeric,"created_at" text);
CREATE TABLE IF NOT EXISTS public."fantasy_lineups" ("id" text PRIMARY KEY,"user_id" text,"league_id" text,"tournament_id" text,"round_number" numeric,"formation" text,"captain_player_id" text,"total_value" numeric,"total_points" numeric,"is_locked" boolean,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."fantasy_player_achievements" ("id" text PRIMARY KEY,"player_profile_id" text,"achievement_id" text,"unlocked_at" text,"match_id" text,"tournament_id" text,"coins_awarded" numeric,"xp_awarded" numeric);
CREATE TABLE IF NOT EXISTS public."fantasy_player_values" ("id" text PRIMARY KEY,"player_profile_id" text,"game_id" text,"market_value" numeric,"previous_value" numeric,"total_fantasy_points" numeric,"matches_played" numeric,"average_points" numeric,"streak_count" numeric,"streak_type" text,"last_match_points" numeric,"volatility_factor" numeric,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."fantasy_rounds" ("id" text PRIMARY KEY,"tournament_id" text,"game_id" text,"round_number" numeric,"name" text,"start_date" text,"end_date" text,"status" text,"created_at" text);
CREATE TABLE IF NOT EXISTS public."fantasy_scoring_config" ("id" text PRIMARY KEY,"game_id" text,"pts_goal" numeric,"pts_assist" numeric,"pts_shot" numeric,"pts_mvp" numeric,"pts_pass" numeric,"pts_tackle" numeric,"pts_save" numeric,"pts_victory" numeric,"pts_draw" numeric,"pts_loss" numeric,"rating_high_threshold" numeric,"rating_high_bonus" numeric,"rating_mid_threshold" numeric,"rating_mid_bonus" numeric,"rating_low_threshold" numeric,"rating_low_penalty" numeric,"tier_multipliers" jsonb,"position_weights" jsonb,"market_factor" numeric,"min_floor_value" numeric,"max_daily_change_pct" numeric,"streak_bonus_pct" numeric,"captain_multiplier" numeric,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."fantasy_teams" ("id" text PRIMARY KEY,"user_id" text,"game_id" text,"team_name" text,"logo_url" text,"coins" numeric,"total_points" numeric,"division" text,"streak_count" numeric,"streak_type" text,"xp" numeric,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."federation_blog_posts" ("id" text PRIMARY KEY,"federation_id" text,"title" text,"content" text,"cover_image_object_key" text,"author_user_id" text,"published" boolean,"created_at" text,"updated_at" text,"category" text,"team_id" text,"player_profile_id" text,"slug" text,"subtitle" text,"tags" jsonb,"source" text,"is_ai_generated" boolean);
CREATE TABLE IF NOT EXISTS public."federation_countries" ("id" text PRIMARY KEY,"federation_id" text,"country_id" text,"created_at" text);
CREATE TABLE IF NOT EXISTS public."federation_customizations" ("id" text PRIMARY KEY,"federation_id" text,"primary_color" text,"secondary_color" text,"accent_color" text,"bg_image_object_key" text,"created_at" text,"updated_at" text,"social_instagram" text,"social_twitter" text,"social_facebook" text,"social_youtube" text,"social_tiktok" text,"social_discord" text,"hero_overlay_opacity" numeric,"hero_overlay_filter" text);
CREATE TABLE IF NOT EXISTS public."federation_followers" ("id" text PRIMARY KEY,"federation_id" text,"user_id" text,"created_at" text);
CREATE TABLE IF NOT EXISTS public."federation_gallery" ("id" text PRIMARY KEY,"federation_id" text,"image_object_key" text,"caption" text,"uploaded_by_user_id" text,"created_at" text,"album_id" text);
CREATE TABLE IF NOT EXISTS public."federation_games" ("id" text PRIMARY KEY,"federation_id" text,"game_id" text,"created_at" text);
CREATE TABLE IF NOT EXISTS public."federation_regulations" ("id" text PRIMARY KEY,"federation_id" text,"template_id" text,"title" text,"content" text,"category" text,"published" boolean,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."federations" ("id" text PRIMARY KEY,"country_id" text,"name" text,"short_name" text,"logo_url" text,"created_at" text,"is_platform" boolean,"is_verified" boolean,"description" text,"region" text,"website" text,"contact" text,"social_links" jsonb);
CREATE TABLE IF NOT EXISTS public."field_edit_costs" ("id" text PRIMARY KEY,"entity_type" text,"field_key" text,"field_label" text,"credit_cost" numeric,"free_edit_mode" text,"free_edit_count" numeric,"free_edit_period_days" numeric,"active" boolean,"created_at" text,"updated_at" text,"renews_per_season" boolean);
CREATE TABLE IF NOT EXISTS public."friendly_betting_config" ("id" text PRIMARY KEY,"enabled" boolean,"house_fee_percent" numeric,"min_stake" numeric,"max_stake" numeric,"allow_in_ranked" boolean,"allow_in_casual" boolean,"stake_matchmaking_mode" text,"stake_tolerance_percent" numeric,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."friendly_config" ("id" text PRIMARY KEY,"enabled" boolean,"max_active_free" numeric,"max_active_pro" numeric,"max_active_ultra" numeric,"cooldown_minutes" numeric,"allow_cross_country" boolean,"allowed_formats" jsonb,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."friendly_listings" ("id" text PRIMARY KEY,"creator_user_id" text,"creator_team_id" text,"mode" text,"game_id" text,"country_id" text,"country_restricted" boolean,"best_of" numeric,"status" text,"scheduled_at" text,"created_at" text,"updated_at" text,"creator_stream_url" text,"is_ranked" boolean,"stake_credits" numeric);
CREATE TABLE IF NOT EXISTS public."friendly_matches" ("id" text PRIMARY KEY,"listing_id" text,"challenger_user_id" text,"challenger_team_id" text,"conversation_id" text,"score_creator" text,"score_challenger" text,"winner_user_id" text,"winner_team_id" text,"status" text,"created_at" text,"updated_at" text,"challenger_stream_url" text,"creator_stream_url" text,"scores" jsonb,"reported_by_user_id" text,"reported_at" text);
CREATE TABLE IF NOT EXISTS public."gallery_albums" ("id" text PRIMARY KEY,"federation_id" text,"name" text,"cover_image_key" text,"created_by_user_id" text,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."game_platforms" ("id" text PRIMARY KEY,"game_id" text,"platform_id" text,"created_at" text);
CREATE TABLE IF NOT EXISTS public."games" ("id" text PRIMARY KEY,"name" text,"genre" text,"participant_type" text,"default_result_mode" text,"default_score_label" text,"min_roster_size" numeric,"max_roster_size" numeric,"created_at" text,"logo_object_key" text,"is_visible" boolean);
CREATE TABLE IF NOT EXISTS public."group_entrants" ("id" text PRIMARY KEY,"stage_group_id" text,"entrant_id" text,"created_at" text);
CREATE TABLE IF NOT EXISTS public."hero_mascot_settings" ("id" text PRIMARY KEY,"image_object_key" text,"width_px" numeric,"height_px" numeric,"is_visible" boolean,"position" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."manual_title_roster" ("id" text PRIMARY KEY,"manual_title_id" text,"player_profile_id" text,"role" text,"created_at" text);
CREATE TABLE IF NOT EXISTS public."manual_titles" ("id" text PRIMARY KEY,"title_name" text,"trophy_image_object_key" text,"federation_id" text,"game_id" text,"tier_id" text,"tournament_id" text,"target_type" text,"team_id" text,"player_profile_id" text,"has_roster" boolean,"awarded_at" text,"created_by" text,"created_at" text,"updated_at" text,"season_id" text);
CREATE TABLE IF NOT EXISTS public."match_eafc_links" ("id" text PRIMARY KEY,"internal_match_id" text,"eafc_match_id" numeric,"game_id" text,"created_by" text,"created_at" text);
CREATE TABLE IF NOT EXISTS public."match_eafc_newgen_player_stats" ("id" text PRIMARY KEY,"internal_match_id" text,"team_id" text,"player_profile_id" text,"platform_handle" text,"club_id" numeric,"player_ea_id" text,"pos" text,"goals" numeric,"assists" numeric,"shots" numeric,"passes_made" numeric,"pass_attempts" numeric,"tackles_made" numeric,"tackle_attempts" numeric,"saves" numeric,"rating" numeric,"mom" boolean,"redcards" numeric,"seconds_played" numeric,"goals_conceded" numeric,"raw_player_json" jsonb,"created_at" text);
CREATE TABLE IF NOT EXISTS public."match_eafc_newgen_team_stats" ("id" text PRIMARY KEY,"internal_match_id" text,"team_id" text,"side" text,"club_id" numeric,"goals" numeric,"goals_against" numeric,"shots" numeric,"passes_made" numeric,"pass_attempts" numeric,"tackles_made" numeric,"tackle_attempts" numeric,"saves" numeric,"rating_sum" numeric,"raw_aggregate_json" jsonb,"created_at" text);
CREATE TABLE IF NOT EXISTS public."match_series" ("id" text PRIMARY KEY,"stage_id" text,"group_id" text,"bracket_round_id" text,"best_of" numeric,"entrant_a_id" text,"entrant_b_id" text,"status" text,"scheduled_at" text,"winner_entrant_id" text,"created_at" text,"score_a" numeric,"score_b" numeric,"round_number" numeric,"match_index" numeric);
CREATE TABLE IF NOT EXISTS public."messenger_theme" ("id" text PRIMARY KEY,"primary_color" text,"secondary_color" text,"accent_color" text,"bubble_sent_color" text,"bubble_received_color" text,"chat_bg_color" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."national_team_players" ("id" text PRIMARY KEY,"national_team_id" text,"player_profile_id" text,"position" text,"status" text,"called_up_by" text,"called_up_at" text,"created_at" text);
CREATE TABLE IF NOT EXISTS public."national_teams" ("id" text PRIMARY KEY,"country_id" text,"game_id" text,"federation_id" text,"name" text,"short_name" text,"logo_url" text,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."org_ranking_config" ("id" text PRIMARY KEY,"federation_id" text,"game_id" text,"entity_type" text,"is_active" boolean,"weight_wins" numeric,"weight_draws" numeric,"weight_losses" numeric,"weight_goals" numeric,"weight_assists" numeric,"weight_rating" numeric,"weight_mvp" numeric,"weight_kills" numeric,"weight_sh_assists" numeric,"weight_damage" numeric,"weight_headshots" numeric,"weight_podiums" numeric,"weight_poles" numeric,"weight_fastest_laps" numeric,"weight_race_points" numeric,"show_wins" boolean,"show_draws" boolean,"show_losses" boolean,"show_goals" boolean,"show_assists" boolean,"show_rating" boolean,"show_mvp" boolean,"show_kills" boolean,"show_sh_assists" boolean,"show_damage" boolean,"show_headshots" boolean,"show_podiums" boolean,"show_poles" boolean,"show_fastest_laps" boolean,"show_race_points" boolean,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."org_template_assignments" ("org_id" text,"template_id" text,"updated_at" text,"is_forced" boolean,"forced_by_user_id" text,"id" text PRIMARY KEY);
CREATE TABLE IF NOT EXISTS public."org_templates" ("id" text PRIMARY KEY,"name" text,"slug" text,"description" text,"preview_image_key" text,"plan_required" text,"is_active" boolean,"sort_order" numeric,"featured" boolean,"created_at" text,"updated_at" text,"is_premium" boolean,"credit_price" text,"is_exclusive_ultra" boolean);
CREATE TABLE IF NOT EXISTS public."performance_achievement_occurrences" ("id" text PRIMARY KEY,"player_profile_id" text,"achievement_type_id" text,"source_type" text,"internal_match_id" text,"team_id" text,"tournament_id" text,"achieved_at" text,"stat_value" numeric,"created_at" text,"period_key" text);
CREATE TABLE IF NOT EXISTS public."performance_achievement_totals" ("player_profile_id" text,"achievement_type_id" text,"total_count" numeric,"updated_at" text,"source_type" text,"period_key" text,"id" text PRIMARY KEY);
CREATE TABLE IF NOT EXISTS public."performance_achievement_types" ("id" text PRIMARY KEY,"code" text,"name" text,"description" text,"scope" text,"icon_object_key" text,"active" boolean,"created_at" text,"updated_at" text,"base_code" text,"period_scope" text,"display_label" text);
CREATE TABLE IF NOT EXISTS public."plan_credit_config" ("id" text PRIMARY KEY,"plan_key" text,"monthly_credits" numeric,"rollover_enabled" boolean,"rollover_max" numeric,"updated_at" text,"weekly_usage_threshold" numeric,"weekly_bonus_credits" numeric);
CREATE TABLE IF NOT EXISTS public."plans" ("id" text PRIMARY KEY,"name" text,"entity_type" text,"tier" text,"price_monthly" numeric,"price_yearly" numeric,"ai_credits_monthly" numeric,"features_json" jsonb,"active" boolean,"sort_order" numeric,"stripe_price_id_monthly" text,"stripe_price_id_yearly" text,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."platforms" ("id" text PRIMARY KEY,"key" text,"name" text,"created_at" text);
CREATE TABLE IF NOT EXISTS public."player_card_gallery" ("id" text PRIMARY KEY,"user_id" text,"player_profile_id" text,"image_object_key" text,"label" text,"is_ai_generated" boolean,"created_at" text);
CREATE TABLE IF NOT EXISTS public."player_imported_stats" ("id" text PRIMARY KEY,"player_profile_id" text,"total_matches" numeric,"total_goals" numeric,"total_assists" numeric,"total_mvp" numeric,"avg_rating" numeric,"imported_at" text,"imported_by" text,"season_id" text);
CREATE TABLE IF NOT EXISTS public."player_profile_change_logs" ("id" text PRIMARY KEY,"player_profile_id" text,"field_name" text,"old_value" text,"new_value" text,"changed_by_user_id" text,"created_at" text);
CREATE TABLE IF NOT EXISTS public."player_profiles" ("id" text PRIMARY KEY,"user_id" text,"country_id" text,"game_id" text,"handle" text,"platform_id" text,"platform_handle" text,"photo_object_key" text,"created_at" text,"tier_id" text,"position" text,"cod_position" numeric);
CREATE TABLE IF NOT EXISTS public."player_templates" ("id" text PRIMARY KEY,"name" text,"slug" text,"description" text,"preview_image_key" text,"plan_required" text,"is_active" boolean,"featured" boolean,"sort_order" numeric,"is_premium" boolean,"credit_price" text,"is_exclusive_ultra" boolean,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."profile_template_assignments" ("id" text PRIMARY KEY,"entity_type" text,"entity_id" text,"template_id" text,"assigned_by" text,"is_forced" boolean,"forced_by_user_id" text,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."ranked_profiles" ("id" text PRIMARY KEY,"user_id" text,"team_id" text,"mode" text,"game_id" text,"elo_rating" numeric,"matches_played" numeric,"wins" numeric,"losses" numeric,"draws" numeric,"win_streak" numeric,"best_streak" numeric,"tier" text,"last_match_at" text,"created_at" text,"country_id" text);
CREATE TABLE IF NOT EXISTS public."ranked_seasons" ("id" text PRIMARY KEY,"name" text,"starts_at" text,"ends_at" text,"is_active" boolean,"created_at" text,"game_id" text,"slug" text,"soft_reset_percent" numeric,"source" text,"season_type" text,"reset_elo" numeric);
CREATE TABLE IF NOT EXISTS public."ranking_hub_cards" ("id" text PRIMARY KEY,"title" text,"description" text,"icon_name" text,"route" text,"sort_order" numeric,"is_active" boolean,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."ranking_seasons" ("id" text PRIMARY KEY,"game_id" text,"name" text,"starts_at" text,"ends_at" text,"is_active" boolean,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."registrations" ("entrant_id" text,"tournament_id" text,"status" text,"created_at" text,"id" text PRIMARY KEY);
CREATE TABLE IF NOT EXISTS public."regulation_templates" ("id" text PRIMARY KEY,"title" text,"content" text,"category" text,"active" boolean,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."roles" ("id" text PRIMARY KEY,"key" text,"name" text);
CREATE TABLE IF NOT EXISTS public."rpc_fn_rnk_top_trophies" ("player_profile_id" text,"handle" text,"display_name" text,"platform_handle" text,"photo_object_key" text,"team_name" text,"matches" numeric,"wins" numeric,"draws" numeric,"losses" numeric,"goals" numeric,"assists" numeric,"mvp" numeric,"rating_sum" numeric,"rating_count" numeric,"trophies" numeric,"id" text PRIMARY KEY);
CREATE TABLE IF NOT EXISTS public."series_games" ("id" text PRIMARY KEY,"series_id" text,"game_number" numeric,"status" text,"score_a" numeric,"score_b" numeric,"decided_by" text,"tiebreak_score_a" numeric,"tiebreak_score_b" numeric,"placement_a" text,"placement_b" text,"winner_entrant_id" text,"created_at" text,"scheduled_at" text);
CREATE TABLE IF NOT EXISTS public."signup_wizard_field_config" ("id" text PRIMARY KEY,"game_id" text,"step_key" text,"field_key" text,"field_label" text,"is_visible" boolean,"is_required" boolean,"sort_order" numeric,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."site_feature_flags" ("id" text PRIMARY KEY,"feature_key" text,"feature_label" text,"feature_group" text,"entity_type" text,"visible" boolean,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."site_settings" ("id" text PRIMARY KEY,"key" text,"value" jsonb,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."social_templates" ("id" text PRIMARY KEY,"name" text,"category" text,"background_image" text,"primary_color" text,"secondary_color" text,"font_family" text,"overlay_opacity" numeric,"active" boolean,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."stage_groups" ("id" text PRIMARY KEY,"stage_id" text,"name" text,"created_at" text);
CREATE TABLE IF NOT EXISTS public."stage_standings" ("id" text PRIMARY KEY,"stage_id" text,"group_id" text,"entrant_id" text,"played" numeric,"wins" numeric,"draws" numeric,"losses" numeric,"score_for" numeric,"score_against" numeric,"score_diff" numeric,"points" numeric,"position" numeric,"created_at" text);
CREATE TABLE IF NOT EXISTS public."states" ("id" text PRIMARY KEY,"country_id" text,"name" text,"code" text,"created_at" text);
CREATE TABLE IF NOT EXISTS public."style_market_stats" ("style_key" text,"max_supply" numeric,"current_supply" numeric,"floor_price" numeric,"avg_recent_price" numeric,"sales_30d" numeric,"last_sale_price" numeric,"last_sale_at" text,"id" text PRIMARY KEY);
CREATE TABLE IF NOT EXISTS public."team_players" ("id" text PRIMARY KEY,"team_id" text,"player_profile_id" text,"role" text,"created_at" text);
CREATE TABLE IF NOT EXISTS public."team_selection_weights" ("id" text PRIMARY KEY,"setting_id" text,"stat_type" text,"weight" numeric);
CREATE TABLE IF NOT EXISTS public."team_selections_results" ("id" text PRIMARY KEY,"setting_id" text,"tournament_id" text,"round_label" text,"period_start" text,"period_end" text,"formation_key" text,"players" jsonb,"image_url" text,"is_published" boolean,"generated_at" text,"created_at" text,"slot_custom_positions" jsonb);
CREATE TABLE IF NOT EXISTS public."team_selections_settings" ("id" text PRIMARY KEY,"tournament_id" text,"name" text,"formation_key" text,"start_date" text,"end_date" text,"min_matches" numeric,"min_minutes" numeric,"is_automatic" boolean,"auto_frequency" text,"is_active" boolean,"created_at" text,"updated_at" text,"slot_position_map" jsonb,"slot_custom_positions" jsonb,"card_width" numeric,"card_height" numeric,"pitch_bg_color" text,"pitch_border_color" text,"pitch_line_color" text,"selection_card_fields_override" jsonb,"pitch_image_url" text,"show_pitch_lines" boolean,"pitch_width" numeric,"pitch_aspect_ratio" text,"is_default" boolean);
CREATE TABLE IF NOT EXISTS public."team_templates" ("id" text PRIMARY KEY,"name" text,"slug" text,"description" text,"preview_image_key" text,"plan_required" text,"is_active" boolean,"featured" boolean,"sort_order" numeric,"is_premium" boolean,"credit_price" text,"is_exclusive_ultra" boolean,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."teams" ("id" text PRIMARY KEY,"owner_user_id" text,"country_id" text,"game_id" text,"name" text,"tag" text,"emblem_object_key" text,"created_at" text,"tier_id" text,"formation" text,"clubsId" numeric,"lineup_assignments" jsonb,"eafc_club_name" text,"eafc_club_platform" text,"eafc_club_members" jsonb);
CREATE TABLE IF NOT EXISTS public."tiers" ("id" text PRIMARY KEY,"key" text,"name" text,"rank" numeric,"created_at" text,"default_trophy_object_key" text);
CREATE TABLE IF NOT EXISTS public."tournament_allowed_tiers" ("id" text PRIMARY KEY,"tournament_id" text,"tier_id" text,"created_at" text);
CREATE TABLE IF NOT EXISTS public."tournament_messenger_config" ("id" text PRIMARY KEY,"game_id" text,"tournament_type" text,"enabled" boolean,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."tournament_stages" ("id" text PRIMARY KEY,"tournament_id" text,"stage_type" text,"stage_order" numeric,"best_of_default" numeric,"result_mode" text,"standings_mode" text,"rules_json" jsonb,"created_at" text);
CREATE TABLE IF NOT EXISTS public."tournaments" ("name" text,"game_id" text,"status" text,"format" text,"created_by_user_id" text,"created_at" text,"starts_at" text,"scope" text,"description" text,"rules_overrides_json" jsonb,"is_easy_mode" boolean,"id" text PRIMARY KEY,"champion_entrant_id" text,"ends_at" text,"country_id" text,"federation_id" text,"registration_open_at" text,"registration_close_at" text,"entry_fee" numeric,"is_free" boolean,"prizes_json" jsonb,"logo_object_key" text,"watermark_opacity" numeric,"watermark_scale" numeric,"transfer_window_status" text,"easy_league_id" text,"participant_mode" text,"is_featured_home" boolean,"featured_until" text,"featured_credits_charged" numeric,"trophy_id" text,"trophy_image_object_key" text,"max_registrations" numeric,"elo_ranking_enabled" boolean,"max_teams_per_user" numeric,"accept_card" boolean,"accept_pix" boolean,"is_special_edition" boolean,"ranking_season_id" text);
CREATE TABLE IF NOT EXISTS public."user_ai_credits" ("created_at" text,"user_id" text,"balance" numeric,"monthly_bonus" numeric,"last_bonus_at" text,"id" text PRIMARY KEY);
CREATE TABLE IF NOT EXISTS public."user_announcement_views" ("created_at" text,"user_id" text,"announcement_key" text,"id" text PRIMARY KEY);
CREATE TABLE IF NOT EXISTS public."user_easy_leagues" ("id" text PRIMARY KEY,"user_id" text,"name" text,"slug" text,"logo_object_key" text,"banner_object_key" text,"theme_template" text,"created_at" text,"updated_at" text);
CREATE TABLE IF NOT EXISTS public."user_roles" ("user_id" text,"role_id" text,"id" text PRIMARY KEY);
CREATE TABLE IF NOT EXISTS public."users_profile" ("id" text PRIMARY KEY,"email" text,"display_name" text,"full_name" text,"preferred_language" text,"created_at" text,"onboarding_completed" boolean);
ALTER TABLE public."ai_feature_costs" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."ai_feature_costs" FROM anon,authenticated;
GRANT ALL ON public."ai_feature_costs" TO service_role;
ALTER TABLE public."avatar_frames" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."avatar_frames" FROM anon,authenticated;
GRANT ALL ON public."avatar_frames" TO service_role;
ALTER TABLE public."avatar_gallery" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."avatar_gallery" FROM anon,authenticated;
GRANT ALL ON public."avatar_gallery" TO service_role;
ALTER TABLE public."avatar_listings" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."avatar_listings" FROM anon,authenticated;
GRANT ALL ON public."avatar_listings" TO service_role;
ALTER TABLE public."avatar_nfts" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."avatar_nfts" FROM anon,authenticated;
GRANT ALL ON public."avatar_nfts" TO service_role;
ALTER TABLE public."avatar_style_limits" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."avatar_style_limits" FROM anon,authenticated;
GRANT ALL ON public."avatar_style_limits" TO service_role;
ALTER TABLE public."avatar_trades" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."avatar_trades" FROM anon,authenticated;
GRANT ALL ON public."avatar_trades" TO service_role;
ALTER TABLE public."bans" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."bans" FROM anon,authenticated;
GRANT ALL ON public."bans" TO service_role;
ALTER TABLE public."bracket_display_config" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."bracket_display_config" FROM anon,authenticated;
GRANT ALL ON public."bracket_display_config" TO service_role;
ALTER TABLE public."bracket_rounds" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."bracket_rounds" FROM anon,authenticated;
GRANT ALL ON public."bracket_rounds" TO service_role;
ALTER TABLE public."brackets" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."brackets" FROM anon,authenticated;
GRANT ALL ON public."brackets" TO service_role;
ALTER TABLE public."champion_roster_snapshots" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."champion_roster_snapshots" FROM anon,authenticated;
GRANT ALL ON public."champion_roster_snapshots" TO service_role;
ALTER TABLE public."combo_effects" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."combo_effects" FROM anon,authenticated;
GRANT ALL ON public."combo_effects" TO service_role;
ALTER TABLE public."cosmetic_bundle_items" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."cosmetic_bundle_items" FROM anon,authenticated;
GRANT ALL ON public."cosmetic_bundle_items" TO service_role;
ALTER TABLE public."cosmetic_bundles" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."cosmetic_bundles" FROM anon,authenticated;
GRANT ALL ON public."cosmetic_bundles" TO service_role;
ALTER TABLE public."cosmetic_collections" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."cosmetic_collections" FROM anon,authenticated;
GRANT ALL ON public."cosmetic_collections" TO service_role;
ALTER TABLE public."cosmetics" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."cosmetics" FROM anon,authenticated;
GRANT ALL ON public."cosmetics" TO service_role;
ALTER TABLE public."countries" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."countries" FROM anon,authenticated;
GRANT ALL ON public."countries" TO service_role;
ALTER TABLE public."credit_packages" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."credit_packages" FROM anon,authenticated;
GRANT ALL ON public."credit_packages" TO service_role;
ALTER TABLE public."credit_transactions" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."credit_transactions" FROM anon,authenticated;
GRANT ALL ON public."credit_transactions" TO service_role;
ALTER TABLE public."draft_plan_limits" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."draft_plan_limits" FROM anon,authenticated;
GRANT ALL ON public."draft_plan_limits" TO service_role;
ALTER TABLE public."drafts" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."drafts" FROM anon,authenticated;
GRANT ALL ON public."drafts" TO service_role;
ALTER TABLE public."eafc_newgen_matches" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."eafc_newgen_matches" FROM anon,authenticated;
GRANT ALL ON public."eafc_newgen_matches" TO service_role;
ALTER TABLE public."eafc_newgen_player_positions" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."eafc_newgen_player_positions" FROM anon,authenticated;
GRANT ALL ON public."eafc_newgen_player_positions" TO service_role;
ALTER TABLE public."easy_tournament_allowed_games" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."easy_tournament_allowed_games" FROM anon,authenticated;
GRANT ALL ON public."easy_tournament_allowed_games" TO service_role;
ALTER TABLE public."easy_tournament_settings" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."easy_tournament_settings" FROM anon,authenticated;
GRANT ALL ON public."easy_tournament_settings" TO service_role;
ALTER TABLE public."ecosystem_game_cards" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."ecosystem_game_cards" FROM anon,authenticated;
GRANT ALL ON public."ecosystem_game_cards" TO service_role;
ALTER TABLE public."elo_federation_seasons" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."elo_federation_seasons" FROM anon,authenticated;
GRANT ALL ON public."elo_federation_seasons" TO service_role;
ALTER TABLE public."elo_season_teams" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."elo_season_teams" FROM anon,authenticated;
GRANT ALL ON public."elo_season_teams" TO service_role;
ALTER TABLE public."elo_season_tiers" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."elo_season_tiers" FROM anon,authenticated;
GRANT ALL ON public."elo_season_tiers" TO service_role;
ALTER TABLE public."elo_tier_version_rules" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."elo_tier_version_rules" FROM anon,authenticated;
GRANT ALL ON public."elo_tier_version_rules" TO service_role;
ALTER TABLE public."entity_slugs" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."entity_slugs" FROM anon,authenticated;
GRANT ALL ON public."entity_slugs" TO service_role;
ALTER TABLE public."entity_visual_overrides" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."entity_visual_overrides" FROM anon,authenticated;
GRANT ALL ON public."entity_visual_overrides" TO service_role;
ALTER TABLE public."entrants" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."entrants" FROM anon,authenticated;
GRANT ALL ON public."entrants" TO service_role;
ALTER TABLE public."fantasy_achievements" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."fantasy_achievements" FROM anon,authenticated;
GRANT ALL ON public."fantasy_achievements" TO service_role;
ALTER TABLE public."fantasy_league_members" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."fantasy_league_members" FROM anon,authenticated;
GRANT ALL ON public."fantasy_league_members" TO service_role;
ALTER TABLE public."fantasy_lineup_players" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."fantasy_lineup_players" FROM anon,authenticated;
GRANT ALL ON public."fantasy_lineup_players" TO service_role;
ALTER TABLE public."fantasy_lineups" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."fantasy_lineups" FROM anon,authenticated;
GRANT ALL ON public."fantasy_lineups" TO service_role;
ALTER TABLE public."fantasy_player_achievements" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."fantasy_player_achievements" FROM anon,authenticated;
GRANT ALL ON public."fantasy_player_achievements" TO service_role;
ALTER TABLE public."fantasy_player_values" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."fantasy_player_values" FROM anon,authenticated;
GRANT ALL ON public."fantasy_player_values" TO service_role;
ALTER TABLE public."fantasy_rounds" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."fantasy_rounds" FROM anon,authenticated;
GRANT ALL ON public."fantasy_rounds" TO service_role;
ALTER TABLE public."fantasy_scoring_config" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."fantasy_scoring_config" FROM anon,authenticated;
GRANT ALL ON public."fantasy_scoring_config" TO service_role;
ALTER TABLE public."fantasy_teams" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."fantasy_teams" FROM anon,authenticated;
GRANT ALL ON public."fantasy_teams" TO service_role;
ALTER TABLE public."federation_blog_posts" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."federation_blog_posts" FROM anon,authenticated;
GRANT ALL ON public."federation_blog_posts" TO service_role;
ALTER TABLE public."federation_countries" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."federation_countries" FROM anon,authenticated;
GRANT ALL ON public."federation_countries" TO service_role;
ALTER TABLE public."federation_customizations" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."federation_customizations" FROM anon,authenticated;
GRANT ALL ON public."federation_customizations" TO service_role;
ALTER TABLE public."federation_followers" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."federation_followers" FROM anon,authenticated;
GRANT ALL ON public."federation_followers" TO service_role;
ALTER TABLE public."federation_gallery" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."federation_gallery" FROM anon,authenticated;
GRANT ALL ON public."federation_gallery" TO service_role;
ALTER TABLE public."federation_games" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."federation_games" FROM anon,authenticated;
GRANT ALL ON public."federation_games" TO service_role;
ALTER TABLE public."federation_regulations" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."federation_regulations" FROM anon,authenticated;
GRANT ALL ON public."federation_regulations" TO service_role;
ALTER TABLE public."federations" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."federations" FROM anon,authenticated;
GRANT ALL ON public."federations" TO service_role;
ALTER TABLE public."field_edit_costs" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."field_edit_costs" FROM anon,authenticated;
GRANT ALL ON public."field_edit_costs" TO service_role;
ALTER TABLE public."friendly_betting_config" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."friendly_betting_config" FROM anon,authenticated;
GRANT ALL ON public."friendly_betting_config" TO service_role;
ALTER TABLE public."friendly_config" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."friendly_config" FROM anon,authenticated;
GRANT ALL ON public."friendly_config" TO service_role;
ALTER TABLE public."friendly_listings" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."friendly_listings" FROM anon,authenticated;
GRANT ALL ON public."friendly_listings" TO service_role;
ALTER TABLE public."friendly_matches" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."friendly_matches" FROM anon,authenticated;
GRANT ALL ON public."friendly_matches" TO service_role;
ALTER TABLE public."gallery_albums" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."gallery_albums" FROM anon,authenticated;
GRANT ALL ON public."gallery_albums" TO service_role;
ALTER TABLE public."game_platforms" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."game_platforms" FROM anon,authenticated;
GRANT ALL ON public."game_platforms" TO service_role;
ALTER TABLE public."games" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."games" FROM anon,authenticated;
GRANT ALL ON public."games" TO service_role;
ALTER TABLE public."group_entrants" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."group_entrants" FROM anon,authenticated;
GRANT ALL ON public."group_entrants" TO service_role;
ALTER TABLE public."hero_mascot_settings" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."hero_mascot_settings" FROM anon,authenticated;
GRANT ALL ON public."hero_mascot_settings" TO service_role;
ALTER TABLE public."manual_title_roster" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."manual_title_roster" FROM anon,authenticated;
GRANT ALL ON public."manual_title_roster" TO service_role;
ALTER TABLE public."manual_titles" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."manual_titles" FROM anon,authenticated;
GRANT ALL ON public."manual_titles" TO service_role;
ALTER TABLE public."match_eafc_links" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."match_eafc_links" FROM anon,authenticated;
GRANT ALL ON public."match_eafc_links" TO service_role;
ALTER TABLE public."match_eafc_newgen_player_stats" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."match_eafc_newgen_player_stats" FROM anon,authenticated;
GRANT ALL ON public."match_eafc_newgen_player_stats" TO service_role;
ALTER TABLE public."match_eafc_newgen_team_stats" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."match_eafc_newgen_team_stats" FROM anon,authenticated;
GRANT ALL ON public."match_eafc_newgen_team_stats" TO service_role;
ALTER TABLE public."match_series" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."match_series" FROM anon,authenticated;
GRANT ALL ON public."match_series" TO service_role;
ALTER TABLE public."messenger_theme" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."messenger_theme" FROM anon,authenticated;
GRANT ALL ON public."messenger_theme" TO service_role;
ALTER TABLE public."national_team_players" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."national_team_players" FROM anon,authenticated;
GRANT ALL ON public."national_team_players" TO service_role;
ALTER TABLE public."national_teams" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."national_teams" FROM anon,authenticated;
GRANT ALL ON public."national_teams" TO service_role;
ALTER TABLE public."org_ranking_config" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."org_ranking_config" FROM anon,authenticated;
GRANT ALL ON public."org_ranking_config" TO service_role;
ALTER TABLE public."org_template_assignments" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."org_template_assignments" FROM anon,authenticated;
GRANT ALL ON public."org_template_assignments" TO service_role;
ALTER TABLE public."org_templates" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."org_templates" FROM anon,authenticated;
GRANT ALL ON public."org_templates" TO service_role;
ALTER TABLE public."performance_achievement_occurrences" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."performance_achievement_occurrences" FROM anon,authenticated;
GRANT ALL ON public."performance_achievement_occurrences" TO service_role;
ALTER TABLE public."performance_achievement_totals" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."performance_achievement_totals" FROM anon,authenticated;
GRANT ALL ON public."performance_achievement_totals" TO service_role;
ALTER TABLE public."performance_achievement_types" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."performance_achievement_types" FROM anon,authenticated;
GRANT ALL ON public."performance_achievement_types" TO service_role;
ALTER TABLE public."plan_credit_config" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."plan_credit_config" FROM anon,authenticated;
GRANT ALL ON public."plan_credit_config" TO service_role;
ALTER TABLE public."plans" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."plans" FROM anon,authenticated;
GRANT ALL ON public."plans" TO service_role;
ALTER TABLE public."platforms" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."platforms" FROM anon,authenticated;
GRANT ALL ON public."platforms" TO service_role;
ALTER TABLE public."player_card_gallery" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."player_card_gallery" FROM anon,authenticated;
GRANT ALL ON public."player_card_gallery" TO service_role;
ALTER TABLE public."player_imported_stats" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."player_imported_stats" FROM anon,authenticated;
GRANT ALL ON public."player_imported_stats" TO service_role;
ALTER TABLE public."player_profile_change_logs" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."player_profile_change_logs" FROM anon,authenticated;
GRANT ALL ON public."player_profile_change_logs" TO service_role;
ALTER TABLE public."player_profiles" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."player_profiles" FROM anon,authenticated;
GRANT ALL ON public."player_profiles" TO service_role;
ALTER TABLE public."player_templates" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."player_templates" FROM anon,authenticated;
GRANT ALL ON public."player_templates" TO service_role;
ALTER TABLE public."profile_template_assignments" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."profile_template_assignments" FROM anon,authenticated;
GRANT ALL ON public."profile_template_assignments" TO service_role;
ALTER TABLE public."ranked_profiles" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."ranked_profiles" FROM anon,authenticated;
GRANT ALL ON public."ranked_profiles" TO service_role;
ALTER TABLE public."ranked_seasons" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."ranked_seasons" FROM anon,authenticated;
GRANT ALL ON public."ranked_seasons" TO service_role;
ALTER TABLE public."ranking_hub_cards" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."ranking_hub_cards" FROM anon,authenticated;
GRANT ALL ON public."ranking_hub_cards" TO service_role;
ALTER TABLE public."ranking_seasons" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."ranking_seasons" FROM anon,authenticated;
GRANT ALL ON public."ranking_seasons" TO service_role;
ALTER TABLE public."registrations" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."registrations" FROM anon,authenticated;
GRANT ALL ON public."registrations" TO service_role;
ALTER TABLE public."regulation_templates" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."regulation_templates" FROM anon,authenticated;
GRANT ALL ON public."regulation_templates" TO service_role;
ALTER TABLE public."roles" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."roles" FROM anon,authenticated;
GRANT ALL ON public."roles" TO service_role;
ALTER TABLE public."rpc_fn_rnk_top_trophies" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."rpc_fn_rnk_top_trophies" FROM anon,authenticated;
GRANT ALL ON public."rpc_fn_rnk_top_trophies" TO service_role;
ALTER TABLE public."series_games" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."series_games" FROM anon,authenticated;
GRANT ALL ON public."series_games" TO service_role;
ALTER TABLE public."signup_wizard_field_config" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."signup_wizard_field_config" FROM anon,authenticated;
GRANT ALL ON public."signup_wizard_field_config" TO service_role;
ALTER TABLE public."site_feature_flags" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."site_feature_flags" FROM anon,authenticated;
GRANT ALL ON public."site_feature_flags" TO service_role;
ALTER TABLE public."site_settings" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."site_settings" FROM anon,authenticated;
GRANT ALL ON public."site_settings" TO service_role;
ALTER TABLE public."social_templates" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."social_templates" FROM anon,authenticated;
GRANT ALL ON public."social_templates" TO service_role;
ALTER TABLE public."stage_groups" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."stage_groups" FROM anon,authenticated;
GRANT ALL ON public."stage_groups" TO service_role;
ALTER TABLE public."stage_standings" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."stage_standings" FROM anon,authenticated;
GRANT ALL ON public."stage_standings" TO service_role;
ALTER TABLE public."states" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."states" FROM anon,authenticated;
GRANT ALL ON public."states" TO service_role;
ALTER TABLE public."style_market_stats" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."style_market_stats" FROM anon,authenticated;
GRANT ALL ON public."style_market_stats" TO service_role;
ALTER TABLE public."team_players" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."team_players" FROM anon,authenticated;
GRANT ALL ON public."team_players" TO service_role;
ALTER TABLE public."team_selection_weights" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."team_selection_weights" FROM anon,authenticated;
GRANT ALL ON public."team_selection_weights" TO service_role;
ALTER TABLE public."team_selections_results" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."team_selections_results" FROM anon,authenticated;
GRANT ALL ON public."team_selections_results" TO service_role;
ALTER TABLE public."team_selections_settings" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."team_selections_settings" FROM anon,authenticated;
GRANT ALL ON public."team_selections_settings" TO service_role;
ALTER TABLE public."team_templates" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."team_templates" FROM anon,authenticated;
GRANT ALL ON public."team_templates" TO service_role;
ALTER TABLE public."teams" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."teams" FROM anon,authenticated;
GRANT ALL ON public."teams" TO service_role;
ALTER TABLE public."tiers" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."tiers" FROM anon,authenticated;
GRANT ALL ON public."tiers" TO service_role;
ALTER TABLE public."tournament_allowed_tiers" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."tournament_allowed_tiers" FROM anon,authenticated;
GRANT ALL ON public."tournament_allowed_tiers" TO service_role;
ALTER TABLE public."tournament_messenger_config" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."tournament_messenger_config" FROM anon,authenticated;
GRANT ALL ON public."tournament_messenger_config" TO service_role;
ALTER TABLE public."tournament_stages" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."tournament_stages" FROM anon,authenticated;
GRANT ALL ON public."tournament_stages" TO service_role;
ALTER TABLE public."tournaments" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."tournaments" FROM anon,authenticated;
GRANT ALL ON public."tournaments" TO service_role;
ALTER TABLE public."user_ai_credits" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."user_ai_credits" FROM anon,authenticated;
GRANT ALL ON public."user_ai_credits" TO service_role;
ALTER TABLE public."user_announcement_views" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."user_announcement_views" FROM anon,authenticated;
GRANT ALL ON public."user_announcement_views" TO service_role;
ALTER TABLE public."user_easy_leagues" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."user_easy_leagues" FROM anon,authenticated;
GRANT ALL ON public."user_easy_leagues" TO service_role;
ALTER TABLE public."user_roles" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."user_roles" FROM anon,authenticated;
GRANT ALL ON public."user_roles" TO service_role;
ALTER TABLE public."users_profile" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."users_profile" FROM anon,authenticated;
GRANT ALL ON public."users_profile" TO service_role;
COMMIT;
NOTIFY pgrst, 'reload schema';