function CreditPackageCards({ user: i, navigate: o, creditBuyLoading: et, setCreditBuyLoading: st }) { const creditRequest = reactExports.useRef(false); const { t: at } = useTranslation(), [vt, Ct] = reactExports.useState(!1), [Tt, Lt] = reactExports.useState(null), [$t, qt] = reactExports.useState(null), [Ht, Gt] = reactExports.useState(null), Kt = usePixCheckout({ onPixGenerated: Ir => { creditRequest.current=false; Gt(Ir), Ct(!1), qt(null); }, onError: Ir => { creditRequest.current=false; ue$1.error("Erro ao gerar PIX: " + Ir), qt(null); } }), { data: tr, isLoading: packagesLoading, error: packageError, refetch: retryPackages } = useQuery({ queryKey: ["credit-packages"], retry: false, queryFn: async () => { let deadline;try { const { data: Ir, error: packageFailure } = await Promise.race([Promise.resolve(supabase.from("credit_packages").select("*").eq("active", !0).order("credits", { ascending: !0 })),new Promise((_,reject)=>{deadline=setTimeout(()=>reject(new Error("Prazo de carregamento excedido")),12000)})]);if(packageFailure)throw packageFailure;return Ir || []; }finally{clearTimeout(deadline);} } }), rr = Ir => { if(creditRequest.current)return; if (!i) {
    o("/login");
    return;
} Lt(Ir), Ct(!0); }, nr = async () => { if (Tt && i && !creditRequest.current && !$t && !Kt.pixLoading) { creditRequest.current=true;
    qt("stripe"), st(Tt);
    try {
        const { data: Ir, error: qr } = await supabase.functions.invoke("purchase-credits", { body: { packageId: Tt } });
        if (qr)
            throw qr;
        if (Ir != null && Ir.client_secret && (Ir != null && Ir.publishable_key))
            o(`/checkout?cs=${encodeURIComponent(Ir.client_secret)}&pk=${encodeURIComponent(Ir.publishable_key)}&return=${encodeURIComponent("/credits/success?credits=purchased")}`);
        else if (Ir != null && Ir.error)
            throw new Error(Ir.error);
    }
    catch (Ir) {
        ue$1.error(at("pricing.errorBuy") + ": " + (Ir.message || ""));
    }
    finally {
        creditRequest.current=false; qt(null), st(null);
    }
} }, jr = () => { if(Tt && i && !creditRequest.current && !$t && !Kt.pixLoading){creditRequest.current=true;qt("pix");try{Kt.requestPix({ paymentType: "credits", packageId: Tt });}catch(error){creditRequest.current=false;qt(null);ue$1.error("Não foi possível iniciar o PIX.");}} }, ir = Ir => `R$ ${(Ir / 100).toFixed(2).replace(".", ",")}`, or = (Ir, qr) => `R$ ${(Ir / 100 / qr).toFixed(2).replace(".", ",")}`, Lr = tr == null ? void 0 : tr.find(Ir => Ir.id === Tt); return jsxRuntimeExports.jsxs(jsxRuntimeExports.Fragment,{children:[packageError?jsxRuntimeExports.jsxs('div',{role:'alert',className:'cbpro-read-error',children:[jsxRuntimeExports.jsx('p',{children:'Não foi possível carregar os pacotes de créditos.'}),jsxRuntimeExports.jsx(Button$1,{onClick:()=>retryPackages(),children:'Tentar novamente'})]}):packagesLoading?jsxRuntimeExports.jsx('p',{role:'status',children:'Carregando pacotes de créditos…'}):tr&&tr.length?jsxRuntimeExports.jsx('ul',{className:'cbpro-credit-offers','aria-label':'Pacotes de créditos',children:tr.map(pack=>jsxRuntimeExports.jsxs('li',{children:[jsxRuntimeExports.jsxs('div',{className:'cbpro-credit-quantity',children:[jsxRuntimeExports.jsx(Coins,{'aria-hidden':true}),jsxRuntimeExports.jsxs('strong',{children:[pack.credits,' ',at('pricing.credits')]})]}),jsxRuntimeExports.jsx('strong',{className:'cbpro-credit-total',children:ir(pack.price_cents)}),jsxRuntimeExports.jsxs('span',{className:'cbpro-credit-unit',children:[or(pack.price_cents,pack.credits),' por crédito']}),jsxRuntimeExports.jsxs(Button$1,{variant:'outline',onClick:()=>rr(pack.id),disabled:et!==null,'aria-label':at('pricing.buy')+' '+pack.credits+' '+at('pricing.credits'),children:[et===pack.id?jsxRuntimeExports.jsx(LoaderCircle,{'aria-hidden':true,className:'animate-spin'}):jsxRuntimeExports.jsx(ArrowRight,{'aria-hidden':true}),at('pricing.buy')]})]},pack.id))}):jsxRuntimeExports.jsx('p',{children:'Nenhum pacote de créditos disponível no momento.'}),jsxRuntimeExports.jsx(PaymentMethodSelector, { open: vt, onOpenChange: Ct, onSelectStripe: nr, onSelectPix: jr, loading: $t, amount: Lr ? (Lr.price_cents / 100).toFixed(2).replace(".", ",") : void 0 }),jsxRuntimeExports.jsx(SavedCpfCnpjModal, { open: Kt.showSavedCpfModal, onOpenChange: Kt.setShowSavedCpfModal, cpfCnpj: Kt.savedCpfCnpj, onUseSaved: Kt.confirmSavedCpfAndCreatePix, onUseDifferent: Kt.useDifferentCpfCnpj, loading: Kt.pixLoading }),jsxRuntimeExports.jsx(CpfCnpjInputModal, { open: Kt.showCpfModal, onOpenChange: Kt.setShowCpfModal, onConfirm: Kt.confirmCpfAndCreatePix, loading: Kt.pixLoading }),Ht && jsxRuntimeExports.jsx(PixCheckoutModal, { open: !!Ht, onOpenChange: Ir => { Ir || Gt(null); }, paymentId: Ht.payment_id, txid: Ht.txid, qrCodeImage: Ht.qr_code_image, pixCopyPaste: Ht.pix_copy_paste, expiresAt: Ht.expires_at, amount: Ht.amount, onPaymentConfirmed: () => { Gt(null), o("/credits/success?credits=purchased"); } })]}); }