function PlanCard({ plan: i, user: o, currentPlan: et, subscribed: st, checkoutLoading: at, portalLoading: vt, onCheckout: Ct, onManage: Tt, navigate: Lt }) { const { t: $t } = useTranslation(), qt = i.tier, Ht = TIER_VISUALS[qt] || TIER_VISUALS.free, Gt = qt === "free" && et === "free", Kt = qt === "pro", tr = qt === "ultra", rr = qt !== "free", nr = Ht.icon, { getHiddenFeatureKeys: jr } = useSiteFeatureFlags(), ir = jr(i.entity_type), or = (FEATURES_BY_ENTITY[i.entity_type] || []).filter(Kr => !ir.has(Kr.key)), Lr = i.features_json, Ir = []; for (const Kr of or) {
    const Zr = Lr[Kr.key], Xr = getFeatureLabel(Kr, $t);
    if (Kr.type === "boolean" && Zr)
        Ir.push(Xr);
    else if (Kr.type === "number" && Zr !== void 0) {
        const _n = Kr.displayValue ? Kr.displayValue(Zr) : String(Zr);
        Ir.push(`${_n} ${Xr.toLowerCase()}`);
    }
    else if (Kr.type === "select" && Zr && Zr !== "null") {
        const _n = Kr.displayValue ? Kr.displayValue(Zr) : Zr;
        Ir.push(`${Xr}: ${_n}`);
    }
} const qr = Ir.slice(0, 8); Ir.length > 8 && qr.push($t("pricing.moreFeatures", { count: Ir.length - 8 })); const Hr = i.price_monthly > 0 ? `$ ${Number(i.price_monthly).toFixed(2)}${$t("pricing.perMonth")}` : $t("pricing.free"), Yr = Kt ? $t("pricing.mostPopular") : tr ? "Premium" : null; return jsxRuntimeExports.jsxs('article',{className:'cbpro-plan-option cbpro-plan-'+qt,children:[jsxRuntimeExports.jsxs('header',{children:[jsxRuntimeExports.jsx(nr,{'aria-hidden':true}),jsxRuntimeExports.jsx('h3',{children:i.name}),jsxRuntimeExports.jsx('p',{className:'cbpro-plan-price',children:Hr})]}),jsxRuntimeExports.jsxs('div',{className:'cbpro-plan-information',children:[i.ai_credits_monthly > 0 && jsxRuntimeExports.jsxs("div", { className: "mb-3 flex items-center gap-2 bg-muted/20 rounded-lg px-3 py-2", children: [jsxRuntimeExports.jsx(Coins, { className: `h-4 w-4 ${Ht.accentClass}` }), jsxRuntimeExports.jsxs("span", { className: "text-xs font-bold", children: [i.ai_credits_monthly, " ", $t("pricing.aiCreditsMonth")] })] }),Gt && o && jsxRuntimeExports.jsxs("div", { className: "mb-4 flex items-center gap-2 bg-emerald-500/10 border border-emerald-500/20 rounded-lg px-3 py-2", children: [jsxRuntimeExports.jsx(Check, { className: "h-4 w-4 text-emerald-400" }), jsxRuntimeExports.jsx("span", { className: "text-xs font-bold text-emerald-400 uppercase", children: $t("pricing.yourCurrentPlan") })] }),jsxRuntimeExports.jsx("ul", { className: "space-y-2 mb-6", children: qr.map(Kr => jsxRuntimeExports.jsxs("li", { className: "flex items-start gap-2 text-sm", children: [jsxRuntimeExports.jsx(Check, { className: `h-4 w-4 mt-0.5 shrink-0 ${Ht.checkClass}` }), jsxRuntimeExports.jsx("span", { className: "text-foreground/80", children: Kr })] }, Kr)) })]}),jsxRuntimeExports.jsx('footer',{children:qt === "free" ? o ? Gt ? jsxRuntimeExports.jsx(Button$1, { variant: "outline", className: "w-full", disabled: !0, children: $t("pricing.planCurrent") }) : null : jsxRuntimeExports.jsx(Button$1, { variant: "outline", className: "w-full", onClick: () => Lt("/login"), children: $t("pricing.startFree") }) : rr ? jsxRuntimeExports.jsxs(Button$1, { className: `w-full font-bold uppercase tracking-wider ${Kt ? "bg-primary hover:bg-primary/90 " : "bg-yellow-500 hover:bg-yellow-500/90 text-black "}`, onClick: () => Ct(i), disabled: at !== null, children: [at === i.id ? jsxRuntimeExports.jsx(LoaderCircle, { className: "h-4 w-4 animate-spin mr-2" }) : jsxRuntimeExports.jsx(Zap, { className: "h-4 w-4 mr-2" }), $t("pricing.subscribe"), " ", i.name] }) : Gt && st ? jsxRuntimeExports.jsxs(Button$1, { variant: "outline", className: "w-full", onClick: Tt, disabled: vt, children: [vt ? jsxRuntimeExports.jsx(LoaderCircle, { className: "h-4 w-4 animate-spin mr-2" }) : jsxRuntimeExports.jsx(Settings, { className: "h-4 w-4 mr-2" }), $t("pricing.manageSub")] }) : null})]}); }