import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';process.env.FC_DATA_DIR=mkdtempSync(join(tmpdir(),'avatar-market-'));
const {save,get,where}=await import('../server/db.mjs');const {invoke}=await import('../server/rpc.mjs');
function fixture(id,overrides={}){save('avatar_nfts',{id,owner_user_id:'seller',total_owners:1});save('avatar_listings',{id,nft_id:id,seller_user_id:'seller',status:'active',price_credits:101,min_price_credits:20,...overrides});return id;}
save('user_ai_credits',{id:'buyer-wallet',user_id:'buyer',balance:500});save('user_ai_credits',{id:'seller-wallet',user_id:'seller',balance:20});const buyer={id:'buyer',role:'member'};
test('avatar purchase settles credits, fee, ownership and ledger exactly once',()=>{fixture('purchase');const result=invoke('buy-avatar-nft',{listing_id:'purchase'},buyer);assert.equal(result.success,true);assert.equal(get('avatar_nfts','purchase').owner_user_id,'buyer');assert.equal(get('avatar_listings','purchase').status,'sold');assert.equal(get('user_ai_credits','buyer-wallet').balance,399);assert.equal(get('user_ai_credits','seller-wallet').balance,110);const trade=where('avatar_trades','listing_id','purchase')[0];assert.equal(trade.platform_fee,11);assert.equal(trade.seller_received,90);assert.equal(where('credit_transactions','trade_id',trade.id).length,2);assert.equal(invoke('buy-avatar-nft',{listing_id:'purchase'},buyer).already_processed,true);assert.equal(get('user_ai_credits','buyer-wallet').balance,399);});
test('own avatar, changed ownership, auctions, invalid prices and insufficient balance do not transfer or charge',()=>{const cases=[['own',{},()=>save('avatar_nfts',{id:'own',owner_user_id:'buyer'})],['changed',{},()=>save('avatar_nfts',{id:'changed',owner_user_id:'other'})],['auction',{},()=>save('avatar_auctions',{id:'auction',nft_id:'auction',status:'active'})],['bad',{price_credits:1.5},()=>{}],['below',{price_credits:10},()=>{}],['poor',{price_credits:1000},()=>{}]];for(const [id,overrides,prepare] of cases){fixture(id,overrides);prepare();const before=get('user_ai_credits','buyer-wallet').balance;assert.throws(()=>invoke('buy-avatar-nft',{listing_id:id},buyer));assert.equal(get('user_ai_credits','buyer-wallet').balance,before);assert.equal(get('avatar_listings',id).status,'active');assert.equal(where('avatar_trades','listing_id',id).length,0);}});
test('unauthenticated and other buyers cannot replay a completed purchase',()=>{assert.throws(()=>invoke('buy-avatar-nft',{listing_id:'purchase'},null),/login/);assert.throws(()=>invoke('buy-avatar-nft',{listing_id:'purchase'},{id:'other'}),/disponível/);});
function offer(id,extra={}){fixture(id);save('avatar_offers',{id,nft_id:id,listing_id:id,seller_user_id:'seller',buyer_user_id:'buyer',offer_credits:50,status:'pending',expires_at:new Date(Date.now()+60000).toISOString(),...extra});}
test('seller accepts offer at negotiated price; repeated acceptance does not charge again',()=>{offer('offer');const before=get('user_ai_credits','buyer-wallet').balance;const result=invoke('accept-offer',{offer_id:'offer',action:'accept'},{id:'seller'});assert.equal(result.success,true);assert.equal(get('avatar_offers','offer').status,'accepted');assert.equal(get('avatar_nfts','offer').owner_user_id,'buyer');assert.equal(get('user_ai_credits','buyer-wallet').balance,before-50);const trade=where('avatar_trades','offer_id','offer')[0];assert.equal(trade.price_credits,50);assert.equal(trade.platform_fee,5);assert.equal(invoke('accept-offer',{offer_id:'offer',action:'accept'},{id:'seller'}).already_processed,true);assert.equal(get('user_ai_credits','buyer-wallet').balance,before-50);});
test('only seller may reject; rejection keeps credits and ownership unchanged',()=>{offer('reject');const before=get('user_ai_credits','buyer-wallet').balance;assert.throws(()=>invoke('accept-offer',{offer_id:'reject',action:'reject'},buyer),/outro vendedor/);assert.equal(invoke('accept-offer',{offer_id:'reject',action:'reject'},{id:'seller'}).success,true);assert.equal(get('avatar_offers','reject').status,'rejected');assert.equal(get('avatar_nfts','reject').owner_user_id,'seller');assert.equal(get('user_ai_credits','buyer-wallet').balance,before);assert.throws(()=>invoke('accept-offer',{offer_id:'reject',action:'accept'},{id:'seller'}),/respondida/);});
test('expired offers and insufficient buyer funds preserve pending offer and ownership',()=>{for(const [id,extra] of [['expired',{expires_at:new Date(0).toISOString()}],['insufficient',{offer_credits:1000}]]){offer(id,extra);const before=get('user_ai_credits','buyer-wallet').balance;assert.throws(()=>invoke('accept-offer',{offer_id:id,action:'accept'},{id:'seller'}));assert.equal(get('avatar_offers',id).status,'pending');assert.equal(get('avatar_nfts',id).owner_user_id,'seller');assert.equal(get('user_ai_credits','buyer-wallet').balance,before);assert.equal(where('avatar_trades','offer_id',id).length,0);}});
