import test from 'node:test';import assert from 'node:assert/strict';import {runCloud} from '../supabase/functions/fc-api/db.mjs';import {matches} from '../supabase/functions/fc-api/query.mjs';import {buyAvatar,decideAvatarOffer} from '../supabase/functions/fc-api/avatar-market.mjs';
import {rest} from '../supabase/functions/fc-api/rest.mjs';
test('cloud avatar settlement commits once after hydration and replay does not charge twice',async()=>{
 const records=new Map([['avatar_nfts:nft',{id:'nft',owner_user_id:'seller',total_owners:1}],['avatar_listings:listing',{id:'listing',nft_id:'nft',seller_user_id:'seller',price_credits:101,status:'active'}],['user_ai_credits:wallet',{id:'wallet',user_id:'buyer',balance:200}]]);let revision=1,commits=0;
 const request=async(name,p)=>{assert.equal(p.p_revision,revision);if(name==='fc_runtime_commit'){commits++;revision++;for(const change of p.p_changes){const key=change.collection+':'+change.id;if(change.action==='delete')records.delete(key);else records.set(key,change.doc);}return {revision};}const rows=[...records].filter(([key])=>key.startsWith(p.p_collection+':')).map(([,row])=>row).filter(row=>matches(row,p.p_filter||{op:'and',children:[]}));return {rows:structuredClone(rows),count:rows.length,offset:0};};
 const buy=async user=>(await runCloud(()=>buyAvatar(user,{listing_id:'listing'}),{request,revision})).result;
 const first=await buy({id:'buyer'});assert.equal(first.success,true);assert.equal(commits,1);assert.equal(records.get('user_ai_credits:wallet').balance,99);assert.equal(records.get('avatar_nfts:nft').owner_user_id,'buyer');
 const seller=[...records.values()].find(row=>row.user_id==='seller'&&row.balance!==undefined);assert.equal(seller.balance,90);
 assert.equal((await buy({id:'buyer'})).already_processed,true);assert.equal(commits,1);await assert.rejects(buy({id:'other'}),/disponível/);assert.equal(commits,1);
 records.set('avatar_nfts:offered',{id:'offered',owner_user_id:'seller'});records.set('avatar_offers:offer',{id:'offer',nft_id:'offered',seller_user_id:'seller',buyer_user_id:'buyer',offer_credits:50,status:'pending',expires_at:new Date(Date.now()+60000).toISOString()});
 const respond=async user=>(await runCloud(()=>decideAvatarOffer(user,{offer_id:'offer',action:'accept'}),{request,revision})).result;
 await assert.rejects(respond({id:'other'}),/outro vendedor/);assert.equal(commits,1);assert.equal((await respond({id:'seller'})).success,true);assert.equal(commits,2);assert.equal(records.get('user_ai_credits:wallet').balance,49);assert.equal(records.get('avatar_offers:offer').status,'accepted');assert.equal(records.get('avatar_nfts:offered').owner_user_id,'buyer');assert.equal((await respond({id:'seller'})).already_processed,true);assert.equal(commits,2);
 records.set('avatar_nfts:new',{id:'new',owner_user_id:'seller',style_key:'style',mint_number:50,total_owners:1,tournament_wins:0});
 const api=async(table,method,input,user)=>(await runCloud(()=>rest(table,method,new URLSearchParams(),input,user,{}),{request,revision})).result;
 const listing=(await api('avatar_listings','POST',{nft_id:'new',seller_user_id:'seller',price_credits:40},{id:'seller',role:'member'})).data[0];assert.equal(listing.status,'active');assert.equal(listing.min_price_credits,5);
 const offer=(await api('avatar_offers','POST',{nft_id:'new',listing_id:listing.id,seller_user_id:'seller',buyer_user_id:'buyer',offer_credits:20},{id:'buyer',role:'member'})).data[0];assert.equal(offer.status,'pending');assert.equal((await api('avatar_offers','GET',{}, {id:'other',role:'member'})).data.length,0);assert.equal((await api('avatar_offers','GET',{}, {id:'seller',role:'member'})).data.length,2);
});
