import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
process.env.FC_DATA_DIR = mkdtempSync(join(tmpdir(), "fc-elo-"));
delete process.env.OPENAI_API_KEY;
delete process.env.AI_API_KEY;
delete process.env.FC_AI_API_KEY;
const { save, get, where, db } = await import("../server/db.mjs");
const { rpc, invoke } = await import("../server/rpc.mjs");
const { spendCredits } = await import("../server/credits.mjs");
const { rest } = await import("../server/rest.mjs");
const { repairEloCatalog } = await import("../server/elo-admin.mjs");
const admin = { id: "admin", role: "admin" };
const member = { id: "member", role: "member" };

test("public tournament list, detail relations and entrant search use local rows", () => {
  const game = save("games", { name: "EA FC" });
  const country = save("countries", { name: "Brasil", iso2: "BR" });
  const federation = save("federations", { name: "Liga Local" });
  const tournament = save("tournaments", { name: "Copa Aberta", status: "REG_OPEN", game_id: game.id, country_id: country.id, federation_id: federation.id, starts_at: "2026-05-01T00:00:00Z" });
  const team = save("teams", { name: "Solo FC", tag: "SOL", game_id: game.id });
  save("entrants", { tournament_id: tournament.id, team_id: team.id, seed: 1 });
  const list = rest("tournaments", "GET", new URLSearchParams({ select: "id,name,status,federations(name),entrants(id,teams(name,tag))", status: "eq.REG_OPEN" }), {}, null, {});
  assert.equal(list.data.length, 1);
  assert.equal(list.data[0].federations.name, "Liga Local");
  assert.equal(list.data[0].entrants[0].teams.tag, "SOL");
  const found = invoke("search-tournament-entrants", { type: "team", names: ["solo fc"], game_id: game.id }, null);
  assert.equal(found.found[0].id, team.id);
});

test("elo organization, config, penalty and transition follow the public admin contract", () => {
  const federation = save("federations", { name: "Fed ELO" });
  const season = save("ranking_seasons", { name: "2026", game_id: "g", is_active: true, starts_at: "2026-01-01", ends_at: "2026-12-31" });
  const id = rpc("fn_initialize_elo_federation_season", { p_federation_id: federation.id, p_season_id: season.id }, admin);
  assert.equal(typeof id, "string");
  assert.equal(rpc("fn_can_manage_elo_federation", { p_federation_id: federation.id }, null), false);
  assert.equal(rpc("fn_can_manage_elo_federation", { p_federation_id: federation.id }, admin), true);
  assert.throws(() => rpc("fn_elo_admin_place_team", { p_federation_season_id: id }, member), /administrativo|login/i);
  const alpha = save("teams", { name: "Alpha", tag: "ALP" });
  const beta = save("teams", { name: "Beta", tag: "BET" });
  const tournament = save("tournaments", { name: "Aberto", federation_id: federation.id, ranking_season_id: season.id, status: "REG_OPEN", elo_ranking_enabled: true });
  save("entrants", { tournament_id: tournament.id, team_id: alpha.id });
  save("entrants", { tournament_id: tournament.id, team_id: beta.id });
  const pending = rpc("fn_elo_admin_pending_teams", { p_federation_season_id: id }, admin);
  assert.equal(pending.length, 2);
  const tiers = where("elo_season_tiers", "federation_season_id", id);
  const t1 = tiers.find(row => row.code === "T1");
  const t2 = tiers.find(row => row.code === "T2");
  const t3 = tiers.find(row => row.code === "T3");
  assert.equal(rpc("fn_bootstrap_elo_v2_from_legacy", { p_federation_season_id: id }, admin).placed, 2);
  assert.throws(() => rpc("fn_bootstrap_elo_v2_from_legacy", { p_federation_season_id: id }, admin), /already has Teams/);
  rpc("fn_elo_admin_place_team", { p_federation_season_id: id, p_team_id: alpha.id, p_season_tier_id: t1.id, p_tier_position: 1 }, admin);
  assert.equal(where("elo_season_teams", "federation_season_id", id).find(row => row.team_id === alpha.id).season_tier_id, t1.id);
  assert.equal(where("elo_season_teams", "federation_season_id", id).find(row => row.team_id === beta.id).season_tier_id, t3.id);
  const finalized = rpc("fn_elo_admin_finalize_organization", { p_federation_season_id: id }, admin);
  assert.equal(finalized.status, "READY");
  rpc("fn_elo_admin_update_season_config", { p_federation_season_id: id, p_k_factor: 24, p_expectation_diff_cap: 300, p_tier_gap: 40, p_tie_policy: "manual", p_secondary_absence_percent: 10, p_secondary_absence_max: 2, p_t1_max_teams: 8, p_t1_initial_elo: 2200, p_t1_promotion_spots: 0, p_t1_relegation_spots: 1, p_t2_max_teams: 8, p_t2_initial_elo: 2000, p_t2_promotion_spots: 1, p_t2_relegation_spots: 1, p_t3_initial_elo: 1800, p_t3_floor_elo: 1600, p_t3_promotion_spots: 1, p_t3_relegation_spots: 0 }, admin);
  assert.equal(get("elo_config_versions", get("elo_federation_seasons", id).current_config_version_id).k_factor, 24);
  const gamma = save("teams", { name: "Gamma" });
  save("entrants", { tournament_id: tournament.id, team_id: gamma.id });
  assert.equal(rpc("fn_elo_admin_place_all_pending_in_t3", { p_federation_season_id: id }, admin), 1);
  assert.equal(where("elo_season_teams", "federation_season_id", id).find(row => row.team_id === gamma.id).season_tier_id, t3.id);
  const delta = save("teams", { name: "Delta", tag: "DEL" });
  rpc("fn_elo_admin_place_team", { p_federation_season_id: id, p_team_id: delta.id, p_season_tier_id: t2.id, p_tier_position: 1 }, admin);
  const main = save("tournaments", { name: "Principal T1", federation_id: federation.id, ranking_season_id: season.id, status: "FINISHED", elo_ranking_enabled: true, starts_at: "2026-06-01" });
  const second = save("tournaments", { name: "Secundario", federation_id: federation.id, ranking_season_id: season.id, status: "FINISHED", elo_ranking_enabled: true, starts_at: "2026-07-01" });
  const lower = save("tournaments", { name: "Principal T3", federation_id: federation.id, ranking_season_id: season.id, status: "FINISHED", elo_ranking_enabled: true, starts_at: "2026-07-02" });
  assert.equal(rpc("fn_elo_admin_has_started_competition", { p_federation_season_id: id }, admin), true);
  assert.throws(() => rpc("fn_elo_admin_place_team", { p_federation_season_id: id, p_team_id: alpha.id, p_season_tier_id: t3.id, p_tier_position: 1 }, admin), /competition in this federation\/season has started/);
  rpc("fn_elo_admin_set_tier_championship", { p_federation_season_id: id, p_season_tier_id: t1.id, p_tournament_id: main.id }, admin);
  rpc("fn_elo_admin_set_tier_championship", { p_federation_season_id: id, p_season_tier_id: t3.id, p_tournament_id: lower.id }, admin);
  const candidates = rpc("fn_elo_admin_principal_tournament_candidates", { p_federation_season_id: id }, admin);
  assert.ok(candidates.some(row => row.tournament_id === main.id && row.tier_code === "T1"));
  const preview = rpc("fn_elo_admin_penalty_preview", { p_federation_season_id: id, p_team_id: alpha.id, p_tournament_id: second.id, p_penalty_type: "SECONDARY_ABSENCE", p_effective_at: "2026-08-01T12:00:00.000Z" }, admin);
  assert.equal(preview.tier_before, "T1");
  assert.equal(preview.elo_after, Math.round(preview.elo_before * 0.9));
  rpc("fn_elo_admin_confirm_penalty", { p_federation_season_id: id, p_team_id: alpha.id, p_tournament_id: second.id, p_penalty_type: "SECONDARY_ABSENCE", p_effective_at: preview.effective_at, p_reason: "Ausencia" }, admin);
  assert.equal(rpc("fn_elo_admin_penalty_events", { p_federation_season_id: id }, admin)[0].team_name, "Alpha");
  const windows = rpc("fn_elo_admin_transition_windows", { p_federation_season_id: id }, admin);
  const boundary = windows.find(row => row.boundary_code === "T1_T2");
  assert.equal(boundary.promotion_spots, 1);
  assert.equal(boundary.relegation_spots, 1);
  const up = save("tournaments", { name: "Principal T2", federation_id: federation.id, ranking_season_id: season.id, status: "FINISHED", elo_ranking_enabled: true });
  rpc("fn_elo_admin_set_tier_championship", { p_federation_season_id: id, p_season_tier_id: t2.id, p_tournament_id: up.id }, admin);
  const windowId = rpc("fn_elo_admin_prepare_transition_window", { p_federation_season_id: id, p_upper_tier_id: t1.id, p_lower_tier_id: t2.id }, admin);
  assert.equal(typeof windowId, "string");
  const snap = where("elo_v2_transition_window_teams", "transition_window_id", windowId);
  const promoted = snap.find(row => row.selection_kind === "PROMOTION");
  const relegated = snap.find(row => row.selection_kind === "RELEGATION");
  assert.ok(promoted && relegated);
  {
    rpc("fn_elo_admin_select_transition_teams", { p_transition_window_id: windowId, p_promoted_team_ids: [promoted.team_id], p_relegated_team_ids: [relegated.team_id] }, admin);
    const transition = rpc("fn_elo_admin_transition_window_preview", { p_transition_window_id: windowId }, admin);
    assert.equal(transition.length, 2);
    rpc("fn_elo_admin_confirm_transition_window", { p_transition_window_id: windowId }, admin);
    assert.equal(get("elo_v2_transition_windows", windowId).status, "CONFIRMED");
  }
  const blockers = rpc("fn_elo_admin_close_preflight", { p_federation_season_id: id }, admin);
  assert.equal(blockers.can_close, false);
  repairEloCatalog();
  assert.equal(where("elo_season_routes", "season_id", season.id)[0].engine_version, "V2");
});

test("club id change, cards, recruitment highlight and shooter ranking are real local operations", () => {
  save("plan_credit_config", { plan_key: "free", monthly_credits: 100 });
  save("ranking_seasons", { name: "Ativa", game_id: "fc", is_active: true, starts_at: "2026-01-01", ends_at: "2026-12-31" });
  save("field_edit_costs", { entity_type: "team", field_key: "club_id_free_changes_per_season", credit_cost: 0, free_edit_count: 1, active: true, renews_per_season: true });
  save("field_edit_costs", { entity_type: "team", field_key: "club_id_change_cost", credit_cost: 50, active: true });
  save("field_edit_costs", { entity_type: "team", field_key: "club_id_different_cost", credit_cost: 10, active: true });
  save("field_edit_costs", { entity_type: "team", field_key: "club_id_very_different_cost", credit_cost: 40, active: true });
  save("ai_feature_costs", { feature_key: "recruitment_team_featured", credit_cost: 10, active: true });
  const owner = { id: "owner", role: "member" };
  save("users_profile", { id: owner.id, display_name: "Dono" });
  save("user_ai_credits", { user_id: owner.id, balance: 100, lifetime_used: 0 });
  const team = save("teams", { name: "Azores Esports", owner_user_id: owner.id, game_id: "fc", clubsId: 10 });
  const preview = rpc("fn_preview_team_club_id_change", { p_team_id: team.id, p_new_club_id: 99, p_new_club_name: "Completely Other Club" }, owner);
  assert.equal(preview.similarity, "VERY_DIFFERENT");
  assert.equal(preview.change_cost, 0);
  assert.equal(preview.similarity_cost, 40);
  const changed = rpc("fn_change_team_club_id", { p_team_id: team.id, p_new_club_id: 99, p_new_club_name: "Completely Other Club", p_request_id: "req-1" }, owner);
  assert.equal(changed.total_cost, 40);
  assert.equal(get("teams", team.id).clubsId, 99);
  assert.equal(rpc("fn_change_team_club_id", { p_team_id: team.id, p_new_club_id: 99, p_new_club_name: "Completely Other Club", p_request_id: "req-1" }, owner).idempotent, true);
  const player = save("player_profiles", { handle: "Ana" });
  save("match_eafc_newgen_player_stats", { player_profile_id: player.id, goals: 2, shots: 4, passes_made: 8, pass_attempts: 10, tackles_made: 3, saves: 0, rating: 8.5, mom: true, raw_player_json: { wins: "1", losses: "0" } });
  const card = rpc("fn_calc_card_stats", { p_player_profile_id: player.id }, null);
  assert.ok(card.overall >= 70);
  assert.equal(card.win_rate, 99);
  const ad = save("recruitment_ads", { user_id: owner.id, ad_type: "team", status: "OPEN", game_id: "fc" });
  const featured = rpc("fn_recruitment_feature_ad", { p_ad_id: ad.id }, owner);
  assert.equal(featured.success, true);
  assert.equal(featured.cost, 10);
  assert.ok(get("recruitment_ads", ad.id).featured_until);
  const cup = save("tournaments", { name: "Shooter", created_by_user_id: owner.id });
  save("shooter_match_reports", { tournament_id: cup.id, player_id: player.id, validated: true, kills: 10, assists: 2, damage: 100, placement: 1 });
  save("shooter_match_reports", { tournament_id: cup.id, player_id: "other", validated: false, kills: 99 });
  assert.equal(rpc("fn_shooter_recalc_leaderboard", { p_tournament_id: cup.id }, owner).rows, 1);
  const board = where("shooter_leaderboard", "tournament_id", cup.id);
  assert.equal(board.length, 1);
  assert.equal(board[0].rank_position, 1);
  assert.equal(board[0].total_kills, 10);
  assert.throws(() => rpc("fn_shooter_recalc_leaderboard", { p_tournament_id: cup.id }, member), /permiss/i);
});

test("stripe and external AI stay disabled without claiming success", () => {
  const user = { id: "payer", role: "member" };
  const status = invoke("stripe-connect-status", { federationId: "fed" }, user);
  assert.equal(status.connected, false);
  assert.equal(status.disabled, true);
  const onboarding = invoke("stripe-connect-onboarding", {}, user);
  assert.match(onboarding.error, /Stripe/);
  assert.throws(() => invoke("ai-tournament-builder", { messages: [] }, user), /IA não configurado/);
  save("ai_feature_costs", { feature_key: "ai_tournament_message", credit_cost: 1, active: true });
  save("user_ai_credits", { user_id: user.id, balance: 20, lifetime_used: 0 });
  assert.throws(() => spendCredits(user, { featureKey: "ai_tournament_message" }), /Nenhum crédito foi consumido/);
  assert.equal(where("user_ai_credits", "user_id", user.id)[0].balance, 20);
});

test.after(() => db.close());
