import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
process.env.FC_DATA_DIR=mkdtempSync(join(tmpdir(),'cbpro-org-'));const {save,get}=await import('../server/db.mjs');const {rest}=await import('../server/rest.mjs');
const owner={id:'owner',role:'member',email:'owner@example.invalid'},stranger={id:'stranger',role:'member',email:'stranger@example.invalid'},staff={id:'staff',role:'member',email:'staff@example.invalid'};
save('federations',{id:'org'});save('user_federations',{user_id:'owner',federation_id:'org',role:'OWNER'});save('user_federations',{user_id:'staff',federation_id:'org',role:'STAFF'});
const call=(method,body,user,filter={})=>rest('org_staff_invites',method,new URLSearchParams(filter),body,user,{});
test('organization owner creates and reads invite; unrelated users and staff cannot manage it',()=>{const row=call('POST',{federation_id:'org',invited_by:'owner',email:'invitee@example.invalid',role:'STAFF'},owner).data[0];assert.equal(row.status,'PENDING');assert.equal(call('GET',{},owner).data.length,1);assert.equal(call('GET',{},stranger).data.length,0);assert.equal(call('GET',{},staff).data.length,0);assert.throws(()=>call('POST',{federation_id:'org',invited_by:'stranger',email:'other@example.invalid',role:'STAFF'},stranger),/permissão/);assert.throws(()=>call('POST',{federation_id:'org',invited_by:'staff',email:'other@example.invalid',role:'STAFF'},staff),/permissão/);});
test('invitee reads own invitation without managing the organization',()=>{const user={id:'invitee',role:'member',email:'invitee@example.invalid'};assert.equal(call('GET',{},user).data.length,1);assert.throws(()=>call('POST',{federation_id:'org',invited_by:user.id,email:'other@example.invalid',role:'STAFF'},user),/permissão/);});
test('owner cannot forge author, promote ADMIN or duplicate pending invite',()=>{assert.throws(()=>call('POST',{federation_id:'org',invited_by:'stranger',email:'other@example.invalid',role:'STAFF'},owner),/Autor/);assert.throws(()=>call('POST',{federation_id:'org',invited_by:'owner',email:'other@example.invalid',role:'ADMIN'},owner),/SUPERADMIN/);assert.throws(()=>call('POST',{federation_id:'org',invited_by:'owner',email:'invitee@example.invalid',role:'STAFF'},owner),/pendente/);});
test('filtered cancellation preserves identity and cannot rewrite or accept invitation directly',()=>{const row=call('GET',{},owner).data[0];assert.throws(()=>call('PATCH',{email:'other@example.invalid',status:'CANCELLED'},owner,{id:'eq.'+row.id}),/cancelamento/);assert.throws(()=>call('PATCH',{status:'ACCEPTED'},owner,{id:'eq.'+row.id}),/cancelamento/);const result=call('PATCH',{status:'CANCELLED',responded_at:new Date().toISOString()},owner,{id:'eq.'+row.id});assert.equal(result.data.length,1);assert.equal(get('org_staff_invites',row.id).status,'CANCELLED');assert.equal(call('PATCH',{status:'CANCELLED'},owner,{id:'eq.missing'}).data.length,0);});
