// PostgREST-compatible filters shared by the cloud adapter and its tests.
export function split(s){let depth=0,quote=false,start=0,out=[];for(let i=0;i<s.length;i++){const c=s[i];if(c==='"')quote=!quote;if(!quote){if(c==='(')depth++;if(c===')')depth--;if(c===','&&depth===0){out.push(s.slice(start,i).trim());start=i+1;}}}out.push(s.slice(start).trim());return out.filter(Boolean);}
export function atom(key,value){if(!/^[a-zA-Z_][\w]*(?:->>?[\w]+)*$/.test(key))throw Object.assign(Error('Campo inválido'),{status:400});let negate=false;if(value.startsWith('not.')){negate=true;value=value.slice(4);}const i=value.indexOf('.'),op=value.slice(0,i),v=value.slice(i+1);if(!['eq','neq','gt','gte','lt','lte','like','ilike','is','in','cs'].includes(op))throw Object.assign(Error('Filtro inválido'),{status:400});return {key:key.replace(/->>?/g,'.'),op,value:op==='in'?split(v.replace(/^\(|\)$/g,'')).map(x=>x.replace(/^"|"$/g,'')):v,negate};}
function group(value,op){return {op,children:split(value.replace(/^\(|\)$/g,'')).map(s=>s.startsWith('and(')?group(s.slice(3),'and'):s.startsWith('or(')?group(s.slice(2),'or'):atom(s.slice(0,s.indexOf('.')),s.slice(s.indexOf('.')+1)))};}
export function filters(query){return {op:'and',children:[...query].filter(([k])=>!['select','order','limit','offset','on_conflict','columns'].includes(k)&&!k.includes('.')).map(([k,v])=>k==='or'||k==='and'?group(v,k):atom(k,v))};}
export const valueAt=(doc,key)=>key.split('.').reduce((v,k)=>v?.[k],doc)??null;
export function matches(doc,f){if(f.children)return f.op==='and'?f.children.every(x=>matches(doc,x)):f.children.some(x=>matches(doc,x));const v=valueAt(doc,f.key),s=v===null?null:typeof v==='object'?JSON.stringify(v):String(v);let ok=false;
 if(f.op==='is')ok=f.value==='null'?v===null:String(v)===f.value;
 else if(v!==null){const needle=f.value;switch(f.op){case 'eq':ok=s===needle;break;case 'neq':ok=s!==needle;break;case 'in':ok=needle.includes(s);break;case 'cs':ok=s.includes(needle);break;case 'like':case 'ilike':{const pattern=needle.split('').map(c=>c==='*'||c==='%'?'.*':c==='_'?'.':c.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('');ok=new RegExp('^'+pattern+'$',f.op==='ilike'?'i':'').test(s);break;}default:{const numeric=/^-?\d+(\.\d+)?$/.test(needle),a=numeric?Number(v):s,b=numeric?Number(needle):needle;ok=f.op==='gt'?a>b:f.op==='gte'?a>=b:f.op==='lt'?a<b:a<=b;}}}
 return f.negate?(v!==null||f.op==='is')&&!ok:ok;
}
