import { readFileSync, writeFileSync } from "fs";
const path = "D:/FC CLUBS/fcclubs/cloud/frontend.js";
let s = readFileSync(path, "utf8");
const helper = `
 const privateRead=new Set(["avatar_offers","fc_audit","fc_system_reports","local_field_edits","local_edit_operations","users_profile","user_roles","user_ai_credits","credit_transactions","direct_messages","direct_conversations","admin_user_permissions","admin_section_permissions","admin_user_feature_access","org_staff_invites","organization_requests","bans","player_profile_change_logs","account_deletion_requests"]);
 const fkTables={country_id:"countries",state_id:"states",game_id:"games",platform_id:"platforms",team_id:"teams",player_profile_id:"player_profiles",user_id:"users_profile",tier_id:"tiers",federation_id:"federations",tournament_id:"tournaments",stage_id:"tournament_stages",group_id:"stage_groups",entrant_id:"entrants",champion_entrant_id:"entrants",home_entrant_id:"entrants",away_entrant_id:"entrants",winner_entrant_id:"entrants",trophy_id:"trophies",series_id:"match_series",bracket_id:"brackets"};
 const splitList=input=>{let depth=0,quote=false,start=0,out=[];for(let i=0;i<input.length;i++){const c=input[i];if(c==='"')quote=!quote;if(!quote){if(c==="(")depth++;if(c===")")depth--;if(c===","&&depth===0){out.push(input.slice(start,i).trim());start=i+1;}}}out.push(input.slice(start).trim());return out.filter(Boolean);};
 const atom=(key,value)=>{let negate=false;if(value.startsWith("not.")){negate=true;value=value.slice(4);}const i=value.indexOf("."),op=value.slice(0,i),v=value.slice(i+1);if(!["eq","neq","gt","gte","lt","lte","like","ilike","is","in","cs"].includes(op))throw Error("filter");return {key:key.replace(/->>?/g,"."),op,value:op==="in"?splitList(v.replace(/^\\(|\\)$/g,"")).map(x=>x.replace(/^"|"$/g,"")):v,negate};};
 const group=(value,op)=>({op,children:splitList(value.replace(/^\\(|\\)$/g,"")).map(s=>s.startsWith("and(")?group(s.slice(3),"and"):s.startsWith("or(")?group(s.slice(2),"or"):atom(s.slice(0,s.indexOf(".")),s.slice(s.indexOf(".")+1)))});
 const filtersOf=query=>({op:"and",children:[...query].filter(([k])=>!["select","order","limit","offset","on_conflict","columns"].includes(k)&&!k.includes(".")).map(([k,v])=>k==="or"||k==="and"?group(v,k):atom(k,v))});
 const baseName=t=>({countries:"country",player_profiles:"player_profile",users_profile:"user",match_series:"series",series_games:"game",tournament_stages:"stage",stage_groups:"group"}[t]||t.replace(/ies$/,"y").replace(/s$/,""));
 async function selectPublic(table,filter,order,limit,offset){const r=await originalFetch(root+"/rest/v1/rpc/fc_public_select",{method:"POST",headers:{apikey:anon,Authorization:"Bearer "+anon,"Content-Type":"application/json"},body:JSON.stringify({p_collection:table,p_filter:filter,p_order:order,p_limit:limit,p_offset:offset})});if(!r.ok)return null;return r.json();}
 async function loadPublic(table,filter,limit){const data=await selectPublic(table,filter,[],limit||5000,0);return data?data.rows||[]:null;}
 async function shapeRows(table,rows,select){if(!select||select==="*")return rows;const tokens=splitList(select),flat=[],embeds=[];for(const token of tokens){const open=token.indexOf("(");if(open>0&&token.endsWith(")"))embeds.push({header:token.slice(0,open),sub:token.slice(open+1,-1)});else flat.push(token);}const out=rows.map(row=>{if(!flat.length||flat.includes("*"))return {...row};const o={};for(const field of flat){const parts=field.split(":");const alias=parts.length>1?parts[0]:field,key=parts.length>1?parts[1]:field;o[alias]=row[key]??null;}return o;});for(const embed of embeds){let header=embed.header,reference=header;if(header.includes(":")){const bits=header.split(":");header=bits[0];reference=bits.slice(1).join(":");}else reference=header.split("!")[0];let target=reference.split("!")[0],hint=reference.split("!")[1];if(hint==="inner"||hint==="left")hint=null;const sample=rows[0]||{};let fk,one=true,back;if(target.endsWith("_id")){fk=target;target=fkTables[fk]||target.replace(/_id$/,"s");}else if(sample[baseName(target)+"_id"]!==undefined){fk=baseName(target)+"_id";}else{one=false;back=baseName(table)+"_id";}if(privateRead.has(target)||target.startsWith("fc_"))continue;if(one){const ids=[...new Set(rows.map(r=>r[fk]).filter(v=>v!=null).map(String))];const related=ids.length?await loadPublic(target,{op:"and",children:[{key:"id",op:"in",value:ids}]},Math.min(10000,ids.length)):[];if(related===null)return null;const shaped=await shapeRows(target,related,embed.sub);const byId=new Map(shaped.map((r,i)=>[String(related[i].id),r]));let keep=[];rows.forEach((row,i)=>{const value=byId.get(String(row[fk]))||null;if(embed.header.split("!").includes("inner")&&!value)return;out[i][header]=value;keep.push(i);});if(embed.header.split("!").includes("inner")){const next=keep.map(i=>out[i]);out.length=0;out.push(...next);}}else{const ids=rows.map(r=>String(r.id));const related=ids.length?await loadPublic(target,{op:"and",children:[{key:back,op:"in",value:ids}]},10000):[];if(related===null)return null;const shaped=await shapeRows(target,related,embed.sub);for(let i=0;i<rows.length;i++){const id=String(rows[i].id);out[i][header]=shaped.filter((_,n)=>String(related[n][back])===id);}}}return out;}
 async function readPublic(url,method){if(method!=="GET"&&method!=="HEAD")return null;let path=url.pathname;if(!(url.origin===new URL(root).origin&&path.startsWith("/rest/v1/"))||path.startsWith("/rest/v1/rpc/"))return null;const table=path.split("/").filter(Boolean).pop();if(!/^[a-z][a-z0-9_]*$/.test(table||"")||privateRead.has(table)||table.startsWith("fc_"))return null;const q=url.searchParams;let limit=Math.min(10000,Math.max(0,Number(q.get("limit")||1000))),offset=Math.max(0,Number(q.get("offset")||0));const range=q.get("range")||"";const order=splitList(q.get("order")||"").filter(Boolean).map(s=>{const [key,direction,empty]=s.split(".");return {key,direction,empty};});let filter;try{filter=filtersOf(q);}catch{return null;}const data=await selectPublic(table,filter,order,limit,offset);if(!data)return null;const rows=await shapeRows(table,data.rows||[],q.get("select")||"*");if(rows===null)return null;const count=data.count??rows.length;const last=rows.length?offset+rows.length-1:offset;const headers={"Content-Type":"application/json","Content-Range":rows.length?\`\${offset}-\${last}/\${count}\`:\`*/\${count}\`};if(method==="HEAD")return new Response(null,{status:200,headers});const single=(q.get("accept")||"").includes("vnd.pgrst.object");if(single){if(rows.length!==1)return new Response(JSON.stringify({code:"PGRST116",message:"JSON object requested, multiple (or no) rows returned"}),{status:406,headers});return new Response(JSON.stringify(rows[0]),{status:200,headers});}return new Response(JSON.stringify(rows),{status:200,headers});}
`;
const needle = "const originalFetch=window.fetch.bind(window);";
if (!s.includes(needle)) throw new Error("needle missing");
if (s.includes("function readPublic")) throw new Error("already patched");
s = s.replace(needle, needle + helper);
const call = "  const direct=await readPublic(url,method);if(direct)return direct;\n";
const mark = "  if(url.origin===location.origin&&url.pathname.startsWith('/api/'))";
if (!s.includes(mark)) throw new Error("api mark missing");
s = s.replace(mark, call + mark);
writeFileSync(path, s);
console.log("bytes", s.length);
