import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
process.loadEnvFile('.env.supabase.local');
const out=path.resolve('../BACKUP-2026-10-01'),ref=process.env.SUPABASE_PROJECT_REF;
fs.mkdirSync(out,{recursive:true});
const save=(name,data)=>{const p=path.join(out,name);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,typeof data==='string'||Buffer.isBuffer(data)?data:JSON.stringify(data,null,2));};
const errors=[];
async function api(route,options={}){for(let i=0;i<4;i++){try{const r=await fetch('https://api.supabase.com/v1/projects/'+ref+route,{...options,headers:{Authorization:'Bearer '+process.env.SUPABASE_ACCESS_TOKEN,'Content-Type':'application/json',...options.headers},signal:AbortSignal.timeout(90000)});if(!r.ok)throw Error('HTTP '+r.status+' '+route);return r;}catch(e){if(i===3)throw e;await new Promise(r=>setTimeout(r,1500*(i+1)));}}}
const sql=async query=>(await api('/database/query',{method:'POST',body:JSON.stringify({query})})).json();
const tables=await sql("select n.nspname schema,c.relname name from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','auth','storage','supabase_migrations') and c.relkind='r' order by 1,2");
save('supabase/tables.json',tables);
const rev=await sql('select * from public.fc_runtime_state');save('supabase/revision-start.json',rev);
const catalogs={columns:"select * from information_schema.columns where table_schema in ('public','auth','storage')",constraints:"select n.nspname schema,c.relname table_name,con.conname,pg_get_constraintdef(con.oid) definition from pg_constraint con join pg_class c on c.oid=con.conrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','auth','storage')",indexes:"select * from pg_indexes where schemaname in ('public','auth','storage')",policies:"select * from pg_policies where schemaname in ('public','auth','storage')",functions:"select n.nspname schema,p.proname name,pg_get_functiondef(p.oid) definition from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prokind='f'",views:"select schemaname,viewname,definition from pg_views where schemaname='public'",grants:"select * from information_schema.role_table_grants where table_schema in ('public','auth','storage')",extensions:"select * from pg_extension",triggers:"select n.nspname schema,c.relname table_name,pg_get_triggerdef(t.oid) definition from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where not t.tgisinternal and n.nspname in ('public','auth','storage')"};
for(const [name,q]of Object.entries(catalogs))save('supabase/schema/'+name+'.json',await sql(q));
for(const t of tables){const existing=path.join(out,`supabase/data/${t.schema}.${t.name}.json`);if(fs.existsSync(existing)){t.rows=JSON.parse(fs.readFileSync(existing,'utf8')).length;continue;}const full='"'+t.schema+'"."'+t.name+'"';try{const rows=[];for(let offset=0;;offset+=2000){const batch=await sql(`select to_jsonb(t) row from ${full} t order by ${t.name==='fc_runtime_records'?'collection,id':'ctid'} limit 2000 offset ${offset}`);rows.push(...batch.map(x=>x.row));if(offset%10000===0)console.log(t.name,offset+batch.length);if(batch.length<2000)break;}save(`supabase/data/${t.schema}.${t.name}.json`,rows);t.rows=rows.length;console.log(t.schema+'.'+t.name,rows.length);}catch(e){errors.push({table:full,error:e.message});}}
save('supabase/tables.json',tables);
for(const route of ['/config/auth','/config/postgres','/functions','/secrets']){try{const d=await(await api(route)).json();save('supabase/config/'+route.slice(1).replaceAll('/','-')+'.json',d);if(route==='/functions')for(const f of d){try{const r=await api('/functions/'+f.slug+'/body');save('supabase/edge/'+f.slug+'.bundle',Buffer.from(await r.arrayBuffer()));}catch(e){errors.push({function:f.slug,error:e.message});}}}catch(e){errors.push({route,error:e.message});}}
const objects=JSON.parse(fs.readFileSync(path.join(out,'supabase/data/storage.objects.json'),'utf8'));let cursor=0,downloaded=0;
await Promise.all(Array.from({length:6},async()=>{while(cursor<objects.length){const o=objects[cursor++];try{const target=path.resolve(out,'supabase/storage',o.bucket_id,o.name);if(!target.startsWith(path.resolve(out,'supabase/storage')+path.sep))throw Error('Invalid object path');const r=await fetch(process.env.SUPABASE_URL+'/storage/v1/object/authenticated/'+encodeURIComponent(o.bucket_id)+'/'+o.name.split('/').map(encodeURIComponent).join('/'),{headers:{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:'Bearer '+process.env.SUPABASE_SERVICE_ROLE_KEY},signal:AbortSignal.timeout(60000)});if(!r.ok)throw Error('HTTP '+r.status);const b=Buffer.from(await r.arrayBuffer());if(o.metadata?.size!=null&&b.length!==Number(o.metadata.size))throw Error('Size mismatch');save(path.relative(out,target),b);downloaded++;}catch(e){errors.push({object:o.bucket_id+'/'+o.name,error:e.message});}}}));
save('supabase/revision-end.json',await sql('select * from public.fc_runtime_state'));
// Preserve deployment source and protected configuration; never publish this backup.
for(const name of ['server','cloud','supabase','scripts','src','tests','public','dist'])if(fs.existsSync(name))fs.cpSync(name,path.join(out,'source',name),{recursive:true});
for(const name of fs.readdirSync('.'))if(fs.statSync(name).isFile()&&(/^(package.*\.json|.*config.*|.*\.md|\.env.*|\.gitignore)$/.test(name)))fs.copyFileSync(name,path.join(out,'source',name));
if(fs.existsSync('data/hostinger-release'))fs.cpSync('data/hostinger-release',path.join(out,'site-local-deployment-copy'),{recursive:true});
save('STATUS.json',{created:new Date().toISOString(),project:ref,tables:tables.length,rows:tables.reduce((n,t)=>n+(t.rows||0),0),objects:objects.length,downloaded,errors,hostinger_live_export:false,format:'logical JSON export, not pg_dump; schema catalogs and source included'});
const manifest=[];function walk(dir){for(const d of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,d.name);if(d.isDirectory())walk(p);else manifest.push({file:path.relative(out,p),size:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});}}walk(out);save('SHA256.json',manifest);console.log('COMPLETE',JSON.stringify({out,downloaded,errors}));
