const fs=require('fs'),ts=require('typescript');
const source=fs.readFileSync('.impeccable/reconstruction/incumbent/Pricing.js','utf8'),ast=ts.createSourceFile('pricing',source,99,true);
const prop=(call,key)=>call.arguments[1].properties.find(p=>p.name?.text===key).initializer;
let declaration;function visit(n){if(ts.isVariableDeclaration(n)&&n.name.getText(ast)==='hx')declaration=n;ts.forEachChild(n,visit)}visit(ast);
const children=prop(declaration.initializer,'children').elements,main=prop(children[1],'children').elements;
const plans=prop(main[1],'children').getText(ast),comparison=main[2].getText(ast),creditParts=prop(main[3].right,'children').elements,dialog=children[2].getText(ast);
const credits=`!o&&jsxRuntimeExports.jsxs('section',{id:'creditos',className:'cbpro-pricing-credits',children:[jsxRuntimeExports.jsx('h2',{children:et('pricing.aiCreditsSection')}),jsxRuntimeExports.jsx('p',{children:et('pricing.aiCreditsDesc')}),${creditParts[1].getText(ast)},${creditParts[2].getText(ast)}]})`;
const choices=`jsxRuntimeExports.jsx('nav',{'aria-label':'Tipo de assinatura',className:'cbpro-pricing-types',children:Xr.map(entity=>jsxRuntimeExports.jsxs('button',{type:'button','aria-pressed':Ht===entity.value,onClick:()=>Gt(entity.value),children:[jsxRuntimeExports.jsx(entity.icon,{'aria-hidden':true}),entity.label]},entity.value))})`;
const hx=`jsxRuntimeExports.jsxs('main',{className:'cbpro-pricing'+(i?' cbpro-pricing-embedded':''),children:[jsxRuntimeExports.jsxs('header',{className:'cbpro-pricing-heading',children:[jsxRuntimeExports.jsx('h1',{children:et('pricing.plansAndPricing')}),jsxRuntimeExports.jsx('p',{children:et('pricing.heroSubtitle')})]}),jsxRuntimeExports.jsxs('div',{className:'cbpro-pricing-workspace',children:[jsxRuntimeExports.jsx('aside',{children:${choices}}),jsxRuntimeExports.jsxs('div',{className:'cbpro-pricing-content',children:[pricingError?jsxRuntimeExports.jsxs('div',{role:'alert',className:'cbpro-read-error',children:[jsxRuntimeExports.jsx('p',{children:'Não foi possível carregar os planos.'}),jsxRuntimeExports.jsx(Button$1,{onClick:()=>retryPricing(),children:'Tentar novamente'})]}):pricingLoading?jsxRuntimeExports.jsx('p',{role:'status',children:'Carregando planos…'}):tx.length?jsxRuntimeExports.jsx('section',{'aria-label':'Planos disponíveis',className:'cbpro-pricing-plans',children:${plans}}):jsxRuntimeExports.jsx('p',{children:'Nenhum plano disponível para esta categoria.'}),!pricingError&&!pricingLoading&&tx.length>0?${comparison}:null,${credits}]})]}),${dialog}]})`;
let output=source.slice(0,declaration.initializer.getStart(ast))+hx+source.slice(declaration.initializer.end);
output=output.replace('{ data: _n = [] } = useQuery','{ data: _n = [], isLoading: pricingLoading, error: pricingError, refetch: retryPricing } = useQuery');
output=output.replace('queryKey: ["pricing-plans"], queryFn:', 'queryKey: ["pricing-plans"], retry: false, queryFn:');
output=output.replace('await supabase.from("plans").select("*").eq("active", !0).order("entity_type").order("sort_order")','await Promise.race([Promise.resolve(supabase.from("plans").select("*").eq("active", !0).order("entity_type").order("sort_order")),new Promise((_,reject)=>setTimeout(()=>reject(new Error("Prazo de carregamento excedido")),12000))])');
output=output.replace('jsxRuntimeExports.jsx(PublicNavbar, {})',require('./credit-result-navigation.cjs').replaceAll('creditResultUser','st'));
output=output.replace('jsxRuntimeExports.jsx(PublicBottomNav, {})','jsxRuntimeExports.jsx(PublicFooter, {})');
// Remove hidden-by-default entrances from retained content so it is visible immediately.
output=output.replace(/initial: \{ opacity: 0, y: (?:20|30) \}, animate: \{ opacity: 1, y: 0 \}, transition: \{[^}]*\}, /g,'');
fs.writeFileSync('src/reconstruction/routes/Pricing.js',output);console.log('Pricing workspace rebuilt; original selection, checkout, portal and credit handlers retained.');
